@startuml hepatitis-model-uz
hide circle
hide empty members
title Gepatit reyestri yozuvi qanday tuzilgan

class HepatitisPatient [[StructureDefinition-hepatitis-patient.html{HepatitisPatient profilini ochish}]] #E8F0FE
class HepatitisEpisodeOfCare [[StructureDefinition-hepatitis-episode-of-care.html{HepatitisEpisodeOfCare profilini ochish}]] #E8F0FE
class HepatitisEncounter [[StructureDefinition-hepatitis-encounter.html{HepatitisEncounter profilini ochish}]] #E8F0FE
class HepatitisCondition [[StructureDefinition-hepatitis-condition.html{HepatitisCondition profilini ochish}]] #E8F0FE
class HepatitisObservationAnalysis [[StructureDefinition-hepatitis-observation-analysis.html{HepatitisObservationAnalysis profilini ochish}]] #E8F0FE
class HepatitisObservationUltraSound [[StructureDefinition-hepatitis-observation-ultra-sound.html{HepatitisObservationUltraSound profilini ochish}]] #E8F0FE
class HepatitisQuestionnaireResponse [[StructureDefinition-hepatitis-questionnaire-response.html{HepatitisQuestionnaireResponse profilini ochish}]] #E8F0FE
class HepatitisQuestionnaire [[StructureDefinition-hepatitis-questionnaire.html{HepatitisQuestionnaire profilini ochish}]] #E8F0FE
class SocioeconomicObservation [[https://dhp.uz/fhir/core/StructureDefinition-uz-core-socioeconomic-observation.html{UZ Core SocioeconomicObservation profilini ochish}]]


HepatitisEpisodeOfCare "0..*" --> "1" HepatitisPatient : « patient »
HepatitisEncounter "0..*" --> "1" HepatitisPatient : « subject »
HepatitisCondition "0..*" --> "1" HepatitisPatient : « subject »
HepatitisEpisodeOfCare "0..*" <-- "0..*" HepatitisEncounter : « episodeOfCare »
HepatitisEpisodeOfCare "0..*" --> "0..*" HepatitisCondition : « diagnosis.condition »
HepatitisCondition "0..*" --> "0..1" HepatitisEncounter : « encounter »
HepatitisPatient "0..1" <-- "0..*" HepatitisObservationAnalysis : « subject »
HepatitisPatient "0..1" <-- "0..*" HepatitisObservationUltraSound : « subject »
HepatitisPatient "0..1" <-- "0..*" HepatitisQuestionnaireResponse : « subject »
HepatitisQuestionnaireResponse "0..*" --> "1" HepatitisQuestionnaire : « questionnaire »
HepatitisQuestionnaireResponse "0..*" --> "0..*" SocioeconomicObservation : « partOf »

caption Klinik graf: diagramma o'qilishi oson bo'lishi uchun tashkilotlar, tibbiyot xodimlari va boshqa ishtirokchilarga havolalar ko'rsatilmagan.

@enduml
