@startuml narcology-model-uz
hide circle
hide empty members
title Narkologiya registri yozuvi qanday tuzilgan

class Patient [[https://dhp.uz/fhir/core/StructureDefinition-uz-core-patient.html{UZ Core Patient profilini ochish}]]
class Encounter [[https://dhp.uz/fhir/core/StructureDefinition-uz-core-encounter.html{UZ Core Encounter profilini ochish}]]
class Condition [[https://dhp.uz/fhir/core/StructureDefinition-uz-core-condition.html{UZ Core Condition profilini ochish}]]
class SocioeconomicObservation [[https://dhp.uz/fhir/core/StructureDefinition-uz-core-socioeconomic-observation.html{UZ Core Socioeconomic Observation profilini ochish}]]
class NarcologyEpisodeOfCare [[StructureDefinition-narcology-episode-of-care.html{NarcologyEpisodeOfCare profilini ochish}]] #E8F0FE
class NarcologyObservation [[StructureDefinition-narcology-observation.html{NarcologyObservation profilini ochish}]] #E8F0FE
class NarcologyPsychiatryFlag [[StructureDefinition-narcology-psychiatry-flag.html{NarcologyPsychiatryFlag profilini ochish}]] #E8F0FE

Patient "1" <-- "0..*" NarcologyEpisodeOfCare : « patient »
Patient "1" <-- "0..*" Condition : « subject »
Patient "1" <-- "0..*" SocioeconomicObservation : « subject »
Patient "1" <-- "0..*" NarcologyObservation : « subject »
Patient "1" <-- "0..*" NarcologyPsychiatryFlag : « subject »
NarcologyEpisodeOfCare "0..1" <-- "0..*" Encounter : « episodeOfCare »
Condition "1" <-- "0..*" NarcologyEpisodeOfCare : « diagnosis.condition »
Encounter "0..1" <-- "0..*" Condition : « encounter »
Encounter "0..1" <-- "0..*" NarcologyObservation : « encounter »
Encounter "0..1" <-- "0..*" NarcologyPsychiatryFlag : « encounter »

@enduml
