@startuml psychiatry-model-en
hide circle
hide empty members
title How a psychiatry registry record fits together

class Patient [[https://dhp.uz/fhir/core/StructureDefinition-uz-core-patient.html{Open the UZ Core Patient profile}]]
class Encounter [[https://dhp.uz/fhir/core/StructureDefinition-uz-core-encounter.html{Open the UZ Core Encounter profile}]]
class SocioeconomicObservation [[https://dhp.uz/fhir/core/StructureDefinition-uz-core-socioeconomic-observation.html{Open the UZ Core Socioeconomic Observation profile}]]
class PsychiatryEpisodeOfCare [[StructureDefinition-psychiatry-episode-of-care.html{Open the PsychiatryEpisodeOfCare profile}]] #E8F0FE
class PsychiatryCondition [[StructureDefinition-psychiatry-condition.html{Open the PsychiatryCondition profile}]] #E8F0FE
class PsychiatryCommissionObservation [[StructureDefinition-psychiatry-commission-observation.html{Open the PsychiatryCommissionObservation profile}]] #E8F0FE
class NarcologyPsychiatryFlag [[StructureDefinition-narcology-psychiatry-flag.html{Open the NarcologyPsychiatryFlag profile}]] #E8F0FE

Patient "1" <-- "0..*" PsychiatryEpisodeOfCare : « patient »
Patient "1" <-- "0..*" PsychiatryCondition : « subject »
Patient "1" <-- "0..*" SocioeconomicObservation : « subject »
Patient "1" <-- "0..*" PsychiatryCommissionObservation : « subject »
Patient "1" <-- "0..*" NarcologyPsychiatryFlag : « subject »
PsychiatryEpisodeOfCare "0..1" <-- "0..*" Encounter : « episodeOfCare »
PsychiatryCondition "1" <-- "0..*" PsychiatryEpisodeOfCare : « diagnosis.condition »
Encounter "0..1" <-- "0..*" PsychiatryCondition : « encounter »
Encounter "0..1" <-- "0..*" PsychiatryCommissionObservation : « encounter »
Encounter "0..1" <-- "0..*" NarcologyPsychiatryFlag : « encounter »

@enduml
