@startuml psychiatry-model-ru
hide circle
hide empty members
title Как устроена запись Психиатрического регистра

class Patient [[https://dhp.uz/fhir/core/StructureDefinition-uz-core-patient.html{Открыть профиль UZ Core Patient}]]
class Encounter [[https://dhp.uz/fhir/core/StructureDefinition-uz-core-encounter.html{Открыть профиль UZ Core Encounter}]]
class SocioeconomicObservation [[https://dhp.uz/fhir/core/StructureDefinition-uz-core-socioeconomic-observation.html{Открыть профиль UZ Core Socioeconomic Observation}]]
class PsychiatryEpisodeOfCare [[StructureDefinition-psychiatry-episode-of-care.html{Открыть профиль PsychiatryEpisodeOfCare}]] #E8F0FE
class PsychiatryCondition [[StructureDefinition-psychiatry-condition.html{Открыть профиль PsychiatryCondition}]] #E8F0FE
class PsychiatryCommissionObservation [[StructureDefinition-psychiatry-commission-observation.html{Открыть профиль PsychiatryCommissionObservation}]] #E8F0FE
class NarcologyPsychiatryFlag [[StructureDefinition-narcology-psychiatry-flag.html{Открыть профиль NarcologyPsychiatryFlag}]] #E8F0FE

Patient "1" <-- "0..*" PsychiatryEpisodeOfCare : « patient »
Patient "1" <-- "0..*" PsychiatryCondition : « subject »
Patient "1" <-- "0..*" SocioeconomicObservation : « subject »
Patient "1" <-- "0..*" PsychiatryCommissionObservation : « subject »
Patient "1" <-- "0..*" NarcologyPsychiatryFlag : « subject »
PsychiatryEpisodeOfCare "0..1" <-- "0..*" Encounter : « episodeOfCare »
PsychiatryCondition "1" <-- "0..*" PsychiatryEpisodeOfCare : « diagnosis.condition »
Encounter "0..1" <-- "0..*" PsychiatryCondition : « encounter »
Encounter "0..1" <-- "0..*" PsychiatryCommissionObservation : « encounter »
Encounter "0..1" <-- "0..*" NarcologyPsychiatryFlag : « encounter »

@enduml
