@startuml psychiatry-model-ru
hide circle
hide empty members
title Как устроена запись психиатрического регистра

class Patient [[https://dhp.uz/fhir/core/StructureDefinition-uz-core-patient.html{Открыть профиль UZ Core Patient}]]
class Encounter [[https://dhp.uz/fhir/core/StructureDefinition-uz-core-encounter.html{Открыть профиль UZ Core Encounter}]]
class SocioeconomicObservation [[https://dhp.uz/fhir/core/StructureDefinition-uz-core-socioeconomic-observation.html{Открыть профиль UZ Core Socioeconomic Observation}]]
class PsychiatryEpisodeOfCare [[StructureDefinition-psychiatry-episode-of-care.html{Открыть профиль PsychiatryEpisodeOfCare}]] #E8F0FE
class PsychiatryCondition [[StructureDefinition-psychiatry-condition.html{Открыть профиль PsychiatryCondition}]] #E8F0FE
class PsychiatryCommissionObservation [[StructureDefinition-psychiatry-commission-observation.html{Открыть профиль PsychiatryCommissionObservation}]] #E8F0FE
class NarcologyPsychiatryFlag [[StructureDefinition-narcology-psychiatry-flag.html{Открыть профиль NarcologyPsychiatryFlag}]] #E8F0FE

Patient "1" <-- "0..*" PsychiatryEpisodeOfCare : « patient »
Patient "1" <-- "0..*" SocioeconomicObservation : « subject »
PsychiatryEpisodeOfCare "0..*" --> "0..*" PsychiatryCondition : « diagnosis.condition »
PsychiatryEpisodeOfCare "0..*" <-- "0..*" Encounter : « episodeOfCare »
Patient "0..1" <-- "0..*" Encounter : « subject »
Patient "1" <-- "0..*" PsychiatryCondition : « subject »
PsychiatryCondition "0..*" <-right- "0..*" Encounter : « diagnosis.condition »
' norank gives this link its own SVG id; two ranked links between the same classes share one
Encounter "0..1" <-[norank]- "0..*" PsychiatryCondition : « encounter »
Encounter "0..1" <--- "0..*" NarcologyPsychiatryFlag : « encounter »
Encounter "0..1" <-- "0..*" PsychiatryCommissionObservation : « encounter »
Patient "1" <-- "0..*" NarcologyPsychiatryFlag : « subject »
Patient "0..1" <-- "0..*" PsychiatryCommissionObservation : « subject »

caption Клинический граф: ссылки на организации, медработников и других участников не показаны, чтобы схема оставалась читаемой.

@enduml
