// Source: QuestionnaireResponse-breast-risk-example.json
Instance: ScreeningBreastRiskResponseExample
InstanceOf: UZCoreQuestionnaireResponse
Usage: #example
Title: "Screening Breast Risk Response Example"
Description: "Example completed response to the Screening breast cancer risk questionnaire."
* id = "screening-breast-risk-response-example"
* language = #ru
* identifier[0].use = #usual
* identifier[0].type.coding[0].system = "http://terminology.hl7.org/CodeSystem/v2-0203"
* identifier[0].type.coding[0].code = #PHC
* identifier[0].type.coding[0].display = "Public Health Case Identifier"
* identifier[0].system = "https://dhp.uz/fhir/core/sid/org/uz/screening"
* identifier[0].value = "136-RMJ"
* questionnaire = "https://dhp.uz/fhir/integrations/Questionnaire/screening-breast-risk"
* status = #completed
* subject.reference = "Patient/lola-oripova"
* subject.display = "Lola Oripova Shakhzodovna"
* encounter.reference = "Encounter/Encounter-onco-followup"
* authored = 2025-11-17T09:18:00+05:00
* author.reference = "PractitionerRole/practitioner-role-nurse"
* source.reference = "Patient/lola-oripova"
* item[0].linkId = "118"
// * item[0].text = "Были ли у вас ранее диагностированы онкологические болезни? (например, опухоли, яичников, лимфомы)"
* item[0].answer[0].valueBoolean = true
* item[1].linkId = "119"
// * item[1].text = "В каком возрасте была первая менструация?"
* item[1].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-breast-questionnaire-answer-cs"
* item[1].answer[0].valueCoding.code = #scrn-0070-00003
* item[1].answer[0].valueCoding.display = "12-13 лет"
* item[2].linkId = "34"
// * item[2].text = "Как вы оцениваете плотность своей груди?"
* item[2].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-breast-questionnaire-answer-cs"
* item[2].answer[0].valueCoding.code = #scrn-0070-00005
* item[2].answer[0].valueCoding.display = "Средняя"
* item[3].linkId = "117"
// * item[3].text = "Есть ли случаи рака молочной железы у родственников первой линии (мать, сестра, дочь)?"
* item[3].answer[0].valueBoolean = false
* item[4].linkId = "120"
// * item[4].text = "В каком возрасте была последняя менструация?"
* item[4].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-breast-questionnaire-answer-cs"
* item[4].answer[0].valueCoding.code = #scrn-0070-00007
* item[4].answer[0].valueCoding.display = "Нет (менопаузы не было)"
* item[5].linkId = "121"
// * item[5].text = "В каком возрасте были первые роды?"
* item[5].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-breast-questionnaire-answer-cs"
* item[5].answer[0].valueCoding.code = #scrn-0070-00011
* item[5].answer[0].valueCoding.display = "До 30 лет"
* item[6].linkId = "122"
// * item[6].text = "Сколько времени вы кормили грудью последнего ребенка?"
* item[6].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-breast-questionnaire-answer-cs"
* item[6].answer[0].valueCoding.code = #scrn-0070-00014
* item[6].answer[0].valueCoding.display = "Свыше 12 месяца"
* item[7].linkId = "123"
// * item[7].text = "Замечали ли вы уплотнения в груди или подмышечной области в последние 3 месяца?"
* item[7].answer[0].valueBoolean = false
* item[8].linkId = "124"
// * item[8].text = "Были ли у вас выделения из соска, не связанные с кормлением?"
* item[8].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-breast-questionnaire-answer-cs"
* item[8].answer[0].valueCoding.code = #scrn-0070-00017
* item[8].answer[0].valueCoding.display = "Нет"
* item[9].linkId = "125"
// * item[9].text = "Изменился ли внешний вид груди (форма, размер,  уплотнение и покраснение кожи, втяжение соска)?"
* item[9].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-breast-questionnaire-answer-cs"
* item[9].answer[0].valueCoding.code = #scrn-0070-00020
* item[9].answer[0].valueCoding.display = "Нет"
* item[10].linkId = "126"
// * item[10].text = "Принимали ли вы гормональные препараты  (противозачаточные, гормональные таблетки во время климакса)"
* item[10].answer[0].valueBoolean = false
* item[11].linkId = "statusRisk"
// * item[11].text = "Рассчитанный риск рака молочной железы"
* item[11].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-risk-level-cs"
* item[11].answer[0].valueCoding.code = #scrn-0081-00001
* item[11].answer[0].valueCoding.display = "Низкий риск"

// Source: QuestionnaireResponse-cervical-risk-example.json
Instance: ScreeningCervicalRiskResponseExample
InstanceOf: UZCoreQuestionnaireResponse
Usage: #example
Title: "Screening Cervical Risk Response Example"
Description: "Example completed response to the Screening cervical cancer risk questionnaire."
* id = "screening-cervical-risk-response-example"
* language = #ru
* identifier[0].use = #usual
* identifier[0].type.coding[0].system = "http://terminology.hl7.org/CodeSystem/v2-0203"
* identifier[0].type.coding[0].code = #PHC
* identifier[0].type.coding[0].display = "Public Health Case Identifier"
* identifier[0].system = "https://dhp.uz/fhir/core/sid/org/uz/screening"
* identifier[0].value = "136-RSHM"
* questionnaire = "https://dhp.uz/fhir/integrations/Questionnaire/screening-cervical-risk"
* status = #completed
* subject.reference = "Patient/lola-oripova"
* subject.display = "Lola Oripova Shakhzodovna"
* encounter.reference = "Encounter/Encounter-onco-followup"
* authored = 2025-11-17T09:18:00+05:00
* author.reference = "PractitionerRole/practitioner-role-nurse"
* source.reference = "Patient/lola-oripova"
* item[0].linkId = "35"
// * item[0].text = "Проводилась ли операция на женских половых органах?"
* item[0].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-cervical-questionnaire-answer-cs"
* item[0].answer[0].valueCoding.code = #scrn-0071-00001
* item[0].answer[0].valueCoding.display = "Не было операций"
* item[1].linkId = "103"
// * item[1].text = "Результат ВПЧ-теста"
* item[1].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-cervical-questionnaire-answer-cs"
* item[1].answer[0].valueCoding.code = #scrn-0071-00008
* item[1].answer[0].valueCoding.display = "Отрицательный"
* item[2].linkId = "104"
// * item[2].text = "Результаты ПАП-теста аномальные?"
* item[2].answer[0].valueBoolean = false
* item[3].linkId = "105"
// * item[3].text = "Ваше семейное положение"
* item[3].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-cervical-questionnaire-answer-cs"
* item[3].answer[0].valueCoding.code = #scrn-0071-00010
* item[3].answer[0].valueCoding.display = "В браке"
* item[4].linkId = "106"
// * item[4].text = "В каком возрасте вы начали половую жизнь?"
* item[4].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-cervical-questionnaire-answer-cs"
* item[4].answer[0].valueCoding.code = #scrn-0071-00015
* item[4].answer[0].valueCoding.display = "После 18 лет"
* item[5].linkId = "36"
// * item[5].text = "Диагностирован ли у вас РШМ в данное время?"
* item[5].answer[0].valueBoolean = false
* item[6].linkId = "37"
// * item[6].text = "Был ли у вас РШМ в анамнезе?"
* item[6].answer[0].valueBoolean = false
* item[7].linkId = "107"
// * item[7].text = "Сколько сексуальных партнеров у вас было?"
* item[7].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-cervical-questionnaire-answer-cs"
* item[7].answer[0].valueCoding.code = #scrn-0071-00016
* item[7].answer[0].valueCoding.display = "1-3"
* item[8].linkId = "41"
// * item[8].text = "Проходили ли вы когда-либо тест на ВПЧ?"
* item[8].answer[0].valueBoolean = true
* item[9].linkId = "108"
// * item[9].text = "Вы были беременны? (Включая выкидыши и аборты)"
* item[9].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-cervical-questionnaire-answer-cs"
* item[9].answer[0].valueCoding.code = #scrn-0071-00019
* item[9].answer[0].valueCoding.display = "Да без выкидышей и абортов"
* item[10].linkId = "109"
// * item[10].text = "Кол-во абортов или выкидышей"
* item[10].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-cervical-questionnaire-answer-cs"
* item[10].answer[0].valueCoding.code = #scrn-0071-00021
* item[10].answer[0].valueCoding.display = "0"
* item[11].linkId = "110"
// * item[11].text = "Вы курите?"
* item[11].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-cervical-questionnaire-answer-cs"
* item[11].answer[0].valueCoding.code = #scrn-0071-00026
* item[11].answer[0].valueCoding.display = "Нет"
* item[12].linkId = "111"
// * item[12].text = "Пользуетесь ли вы методами контрацепции?"
* item[12].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-cervical-questionnaire-answer-cs"
* item[12].answer[0].valueCoding.code = #scrn-0071-00031
* item[12].answer[0].valueCoding.display = "Презервативы"
* item[13].linkId = "112"
// * item[13].text = "Были ли у вас когда-нибудь инфекции, передающиеся половым путем?"
* item[13].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-cervical-questionnaire-answer-cs"
* item[13].answer[0].valueCoding.code = #scrn-0071-00034
* item[13].answer[0].valueCoding.display = "Нет"
* item[14].linkId = "113"
// * item[14].text = "Была ли у вас когда-нибудь обнаружена ВИЧ-инфекция?"
* item[14].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-cervical-questionnaire-answer-cs"
* item[14].answer[0].valueCoding.code = #scrn-0071-00037
* item[14].answer[0].valueCoding.display = "Нет"
* item[15].linkId = "114"
// * item[15].text = "Были ли у вашей матери или сестер РШМ?"
* item[15].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-cervical-questionnaire-answer-cs"
* item[15].answer[0].valueCoding.code = #scrn-0071-00040
* item[15].answer[0].valueCoding.display = "Нет"
* item[16].linkId = "115"
// * item[16].text = "Проводилась ли вам вакцинация от ВПЧ?"
* item[16].answer[0].valueBoolean = true
* item[17].linkId = "116"
// * item[17].text = "Были ли у вас контактные кровотечения?"
* item[17].answer[0].valueBoolean = true
* item[18].linkId = "statusRisk"
// * item[18].text = "Рассчитанный риск рака шейки матки"
* item[18].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-risk-level-cs"
* item[18].answer[0].valueCoding.code = #scrn-0081-00001
* item[18].answer[0].valueCoding.display = "Низкий риск"

// Source: QuestionnaireResponse-woman-exam-128.json
Instance: ScreeningWomanExamResponse128
InstanceOf: UZCoreQuestionnaireResponse
Usage: #example
Title: "Screening Woman Examination Response Example"
Description: "Example completed response to the Screening woman examination questionnaire."
* id = "screening-woman-exam-response-128"
* language = #ru
* identifier[0].use = #usual
* identifier[0].type.coding[0].system = "http://terminology.hl7.org/CodeSystem/v2-0203"
* identifier[0].type.coding[0].code = #PHC
* identifier[0].type.coding[0].display = "Public Health Case Identifier"
* identifier[0].system = "https://dhp.uz/fhir/core/sid/org/uz/screening"
* identifier[0].value = "128"
* identifier[1].system = "https://dhp.uz/fhir/integrations/sid/screening/form025-id"
* identifier[1].value = "117"
* questionnaire = "https://dhp.uz/fhir/integrations/Questionnaire/screening-woman-exam"
* status = #completed
* authored = 2026-01-21T05:07:15.806Z
* author.identifier.system = "https://dhp.uz/fhir/core/sid/uz/pinfl"
* author.identifier.value = "31705584220029"
* author.display = "ABDUMALIK KHASHIMOV MUYDINOVICH"
* item[0].linkId = "complaints"
* item[0].text = "Жалобы"
* item[0].item[0].linkId = "cervical-complaints"
* item[0].item[0].text = "Жалобы по шейке матки"
* item[0].item[0].item[0].linkId = "cervical-postcoital-bleeding"
* item[0].item[0].item[0].text = "Кровянистые выделения после полового контакта"
* item[0].item[0].item[0].answer[0].valueBoolean = true
* item[0].item[0].item[1].linkId = "cervical-acyclic-bleeding"
* item[0].item[0].item[1].text = "Кровянистые выделения вне зависимости от менструального цикла (ациклические)"
* item[0].item[0].item[1].answer[0].valueBoolean = true
* item[0].item[0].item[2].linkId = "cervical-watery-discharge"
* item[0].item[0].item[2].text = "Водянистые выделения из половых путей"
* item[0].item[0].item[2].answer[0].valueBoolean = true
* item[0].item[0].item[3].linkId = "cervical-leg-edema"
* item[0].item[0].item[3].text = "Отеки нижних конечностей"
* item[0].item[0].item[3].answer[0].valueBoolean = true
* item[0].item[0].item[4].linkId = "cervical-menstrual-dysfunction"
* item[0].item[0].item[4].text = "Нарушение менструальной функции"
* item[0].item[0].item[4].answer[0].valueBoolean = true
* item[0].item[0].item[5].linkId = "cervical-menopausal-bleeding"
* item[0].item[0].item[5].text = "Кровянистые выделения из половых путей во время менопаузы"
* item[0].item[0].item[5].answer[0].valueBoolean = true
* item[0].item[0].item[6].linkId = "cervical-lower-abdominal-back-pain"
* item[0].item[0].item[6].text = "Боли внизу живота, в пояснице"
* item[0].item[0].item[6].answer[0].valueBoolean = true
* item[0].item[0].item[7].linkId = "cervical-complaints-onset"
* item[0].item[0].item[7].text = "Когда начали беспокоить вышеуказанные жалобы?"
* item[0].item[0].item[7].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-medical-exam-complaint-onset-cs"
* item[0].item[0].item[7].answer[0].valueCoding.code = #scrn-0001-00001
* item[0].item[0].item[7].answer[0].valueCoding.display = "До 3-х месяцев"
* item[0].item[1].linkId = "breast-complaints"
* item[0].item[1].text = "Жалобы по молочной железе"
* item[0].item[1].item[0].linkId = "breast-lump-or-axillary-mass"
* item[0].item[1].item[0].text = "Уплотнение или наличие образования в молочной железе, в подмышечной области"
* item[0].item[1].item[0].answer[0].valueBoolean = true
* item[0].item[1].item[1].linkId = "breast-skin-retraction-or-peau-dorange"
* item[0].item[1].item[1].text = "Изменения в кожном покрове: втяжение кожи, припухлость, кожа в виде «лимонной корки»"
* item[0].item[1].item[1].answer[0].valueBoolean = true
* item[0].item[1].item[2].linkId = "breast-skin-color-thickening-edema"
* item[0].item[1].item[2].text = "Изменения цвета кожи: покраснение, утолщение и нагрубание кожи, появление отёка"
* item[0].item[1].item[2].answer[0].valueBoolean = true
* item[0].item[1].item[3].linkId = "breast-nipple-retraction-flattening"
* item[0].item[1].item[3].text = "Изменения соска: втяжение или уплощение соска"
* item[0].item[1].item[3].answer[0].valueBoolean = true
* item[0].item[1].item[4].linkId = "breast-nipple-crust"
* item[0].item[1].item[4].text = "Появление корочки на коже соска"
* item[0].item[1].item[4].answer[0].valueBoolean = true
* item[0].item[1].item[5].linkId = "breast-serous-or-bloody-discharge"
* item[0].item[1].item[5].text = "Выделения из соска сукровичного или кровянистого характера"
* item[0].item[1].item[5].answer[0].valueBoolean = true
* item[0].item[1].item[6].linkId = "breast-shape-change"
* item[0].item[1].item[6].text = "Изменения формы молочной железы: деформация, увеличение молочной железы"
* item[0].item[1].item[6].answer[0].valueBoolean = true
* item[0].item[1].item[7].linkId = "breast-pain"
* item[0].item[1].item[7].text = "Боль в груди"
* item[0].item[1].item[7].answer[0].valueBoolean = true
* item[0].item[1].item[8].linkId = "breast-complaints-onset"
* item[0].item[1].item[8].text = "Когда начали беспокоить вышеуказанные жалобы?"
* item[0].item[1].item[8].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-medical-exam-complaint-onset-cs"
* item[0].item[1].item[8].answer[0].valueCoding.code = #scrn-0001-00001
* item[0].item[1].item[8].answer[0].valueCoding.display = "До 3-х месяцев"
* item[1].linkId = "vitae-anamnesis"
* item[1].text = "Анамнез Vitae"
* item[1].item[0].linkId = "childhood-infections"
* item[1].item[0].text = "Перенесённые инфекции в детстве"
* item[1].item[0].answer[0].valueCoding.system = $sct
* item[1].item[0].answer[0].valueCoding.code = #14189004
* item[1].item[0].answer[1].valueCoding.system = $sct
* item[1].item[0].answer[1].valueCoding.code = #3738000
* item[1].item[0].answer[2].valueCoding.system = $sct
* item[1].item[0].answer[2].valueCoding.code = #195677001
* item[1].item[0].answer[3].valueCoding.system = $sct
* item[1].item[0].answer[3].valueCoding.code = #54398005
* item[1].item[1].linkId = "childhood-infections-comment"
* item[1].item[1].text = "Перенесённые инфекции в детстве (комментарий)"
* item[1].item[1].answer[0].valueString = "1"
* item[1].item[2].linkId = "previous-diseases"
* item[1].item[2].text = "Перенесённые болезни"
* item[1].item[2].answer[0].valueString = "1"
* item[1].item[3].linkId = "previous-operations"
* item[1].item[3].text = "Перенесённые операции"
* item[1].item[3].answer[0].valueCoding.system = $sct
* item[1].item[3].answer[0].valueCoding.code = #80146002
* item[1].item[4].linkId = "previous-operations-comment"
* item[1].item[4].text = "Перенесённые операции (комментарий)"
* item[1].item[4].answer[0].valueString = "1"
* item[1].item[5].linkId = "hereditary-diseases"
* item[1].item[5].text = "Наследственные болезни"
* item[1].item[5].answer[0].valueBoolean = true
* item[1].item[6].linkId = "hereditary-diseases-comment"
* item[1].item[6].text = "Наследственные болезни (комментарий)"
* item[1].item[6].answer[0].valueString = "1"
* item[1].item[7].linkId = "blood-transfusion"
* item[1].item[7].text = "Переливание крови"
* item[1].item[7].answer[0].valueBoolean = true
* item[1].item[8].linkId = "blood-transfusion-comment"
* item[1].item[8].text = "Переливание крови (комментарий)"
* item[1].item[8].answer[0].valueString = "1"
* item[1].item[9].linkId = "allergic-reactions"
* item[1].item[9].text = "Аллергические реакции"
* item[1].item[9].answer[0].valueBoolean = true
* item[1].item[10].linkId = "allergic-reactions-comment"
* item[1].item[10].text = "Аллергические реакции (комментарий)"
* item[1].item[10].answer[0].valueString = "1"
* item[1].item[11].linkId = "menarche-age"
* item[1].item[11].text = "Возраст начала менструаций"
* item[1].item[11].answer[0].valueInteger = 1
* item[1].item[12].linkId = "menstruation-regular"
* item[1].item[12].text = "Регулярная менструация"
* item[1].item[12].answer[0].valueBoolean = true
* item[1].item[13].linkId = "menstrual-cycle-duration"
* item[1].item[13].text = "Длительность цикла (дней)"
* item[1].item[13].answer[0].valueInteger = 1
* item[1].item[14].linkId = "menstruation-painfulness"
* item[1].item[14].text = "Болезненность менструаций"
* item[1].item[14].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-menstruation-painfulness-cs"
* item[1].item[14].answer[0].valueCoding.code = #scrn-0004-00002
* item[1].item[14].answer[0].valueCoding.display = "Безболезненный"
* item[1].item[15].linkId = "menstruation-abundance"
* item[1].item[15].text = "Обильность менструаций"
* item[1].item[15].answer[0].valueCoding.system = $sct
* item[1].item[15].answer[0].valueCoding.code = #308550003
* item[1].item[16].linkId = "menstruation-onset-after-days"
* item[1].item[16].text = "После скольких дней наступает менструация"
* item[1].item[16].answer[0].valueInteger = 0
* item[2].linkId = "breast-exam"
* item[2].text = "Осмотр молочных желез"
* item[2].item[0].linkId = "breast-pain-group"
* item[2].item[0].text = "Болевые ощущения (мастодиния/масталгия)"
* item[2].item[0].item[0].linkId = "breast-aching-pulling-burning-pain"
* item[2].item[0].item[0].text = "Ноющая, тянущая или жгучая боль"
* item[2].item[0].item[0].answer[0].valueBoolean = true
* item[2].item[0].item[1].linkId = "breast-cyclic-or-constant-pain"
* item[2].item[0].item[1].text = "Циклическая (усиливается перед менструацией) или постоянная"
* item[2].item[0].item[1].answer[0].valueBoolean = true
* item[2].item[0].item[2].linkId = "breast-local-or-diffuse-pain"
* item[2].item[0].item[2].text = "Локальная или разлитая"
* item[2].item[0].item[2].answer[0].valueBoolean = true
* item[2].item[1].linkId = "breast-changes"
* item[2].item[1].text = "Изменения в молочных железах"
* item[2].item[1].item[0].linkId = "breast-palpable-lump"
* item[2].item[1].item[0].text = "Уплотнение или «шарик» при пальпации"
* item[2].item[1].item[0].answer[0].valueBoolean = true
* item[2].item[1].item[1].linkId = "breast-unilateral-enlargement-asymmetry"
* item[2].item[1].item[1].text = "Увеличение или асимметрия одной железы"
* item[2].item[1].item[1].answer[0].valueBoolean = true
* item[2].item[1].item[2].linkId = "breast-swelling"
* item[2].item[1].item[2].text = "Отёчность"
* item[2].item[1].item[2].answer[0].valueBoolean = true
* item[2].item[1].item[3].linkId = "breast-heaviness"
* item[2].item[1].item[3].text = "Ощущение тяжести"
* item[2].item[1].item[3].answer[0].valueBoolean = true
* item[2].item[2].linkId = "breast-skin-nipple-changes"
* item[2].item[2].text = "Изменения кожи и соска"
* item[2].item[2].item[0].linkId = "breast-skin-or-nipple-retraction"
* item[2].item[2].item[0].text = "Втяжение кожи или соска"
* item[2].item[2].item[0].answer[0].valueBoolean = true
* item[2].item[2].item[1].linkId = "breast-redness"
* item[2].item[2].item[1].text = "Покраснение"
* item[2].item[2].item[1].answer[0].valueBoolean = true
* item[2].item[2].item[2].linkId = "breast-induration-peau-dorange"
* item[2].item[2].item[2].text = "Уплотнение, «лимонная корка»"
* item[2].item[2].item[2].answer[0].valueBoolean = true
* item[2].item[2].item[3].linkId = "breast-desquamation-ulceration"
* item[2].item[2].item[3].text = "Шелушение, язвочки"
* item[2].item[2].item[3].answer[0].valueBoolean = true
* item[2].item[3].linkId = "nipple-discharge-type"
* item[2].item[3].text = "Выделения из сосков"
* item[2].item[3].item[0].linkId = "nipple-discharge-transparent"
* item[2].item[3].item[0].text = "Прозрачные"
* item[2].item[3].item[0].answer[0].valueBoolean = true
* item[2].item[3].item[1].linkId = "nipple-discharge-milky"
* item[2].item[3].item[1].text = "Молочные"
* item[2].item[3].item[1].answer[0].valueBoolean = true
* item[2].item[3].item[2].linkId = "nipple-discharge-yellowish"
* item[2].item[3].item[2].text = "Желтоватые"
* item[2].item[3].item[2].answer[0].valueBoolean = true
* item[2].item[3].item[3].linkId = "nipple-discharge-greenish"
* item[2].item[3].item[3].text = "Зеленоватые"
* item[2].item[3].item[3].answer[0].valueBoolean = true
* item[2].item[3].item[4].linkId = "nipple-discharge-bloody"
* item[2].item[3].item[4].text = "Кровянистые"
* item[2].item[3].item[4].answer[0].valueBoolean = true
* item[2].item[4].linkId = "breast-inflammatory"
* item[2].item[4].text = "Воспалительные проявления"
* item[2].item[4].item[0].linkId = "breast-inflammatory-redness"
* item[2].item[4].item[0].text = "Покраснение"
* item[2].item[4].item[0].answer[0].valueBoolean = true
* item[2].item[4].item[1].linkId = "breast-local-or-general-fever"
* item[2].item[4].item[1].text = "Повышение температуры местно и/или общего тела"
* item[2].item[4].item[1].answer[0].valueBoolean = true
* item[2].item[4].item[2].linkId = "breast-engorgement-or-abscess"
* item[2].item[4].item[2].text = "Нагрубание, абсцесс (гнойные выделения)"
* item[2].item[4].item[2].answer[0].valueBoolean = true
* item[2].item[5].linkId = "breast-subjective-sensations"
* item[2].item[5].text = "Субъективные ощущения"
* item[2].item[5].item[0].linkId = "breast-tension-sensation"
* item[2].item[5].item[0].text = "Чувство напряжения"
* item[2].item[5].item[0].answer[0].valueBoolean = true
* item[2].item[5].item[1].linkId = "breast-distension-sensation"
* item[2].item[5].item[1].text = "Чувство распирания"
* item[2].item[5].item[1].answer[0].valueBoolean = true
* item[2].item[5].item[2].linkId = "nipple-hypersensitivity"
* item[2].item[5].item[2].text = "Повышенная чувствительность сосков"
* item[2].item[5].item[2].answer[0].valueBoolean = true
* item[2].item[5].item[3].linkId = "breast-foreign-body-sensation"
* item[2].item[5].item[3].text = "Ощущение «инородного тела»"
* item[2].item[5].item[3].answer[0].valueBoolean = true
* item[2].item[6].linkId = "breast-lymph-nodes"
* item[2].item[6].text = "Состояние лимфатических узлов"
* item[2].item[6].item[0].linkId = "axillary-nodes-bilateral-palpable"
* item[2].item[6].item[0].text = "Подмышечные лимфатические узлы пальпируются с обеих сторон"
* item[2].item[6].item[0].answer[0].valueBoolean = true
* item[2].item[6].item[1].linkId = "axillary-nodes-unilateral-palpable"
* item[2].item[6].item[1].text = "Подмышечные лимфатические узлы пальпируются с одной стороны"
* item[2].item[6].item[1].answer[0].valueBoolean = true
* item[2].item[6].item[2].linkId = "supraclavicular-nodes-palpable"
* item[2].item[6].item[2].text = "Пальпируются надключичные лимфатические узлы"
* item[2].item[6].item[2].answer[0].valueBoolean = true
* item[2].item[6].item[3].linkId = "infraclavicular-nodes-palpable"
* item[2].item[6].item[3].text = "Пальпируются подключичные лимфатические узлы"
* item[2].item[6].item[3].answer[0].valueBoolean = true
* item[3].linkId = "menstruation-exam"
* item[3].text = "Менструации во время обследования"
* item[3].item[0].linkId = "regular-menstruation"
* item[3].item[0].text = "Характер при обследовании (регулярные)"
* item[3].item[0].item[0].linkId = "regular-menstruation-start-age"
* item[3].item[0].item[0].text = "Возраст начала менструаций (регулярные)"
* item[3].item[0].item[0].answer[0].valueInteger = 0
* item[3].item[0].item[1].linkId = "regular-menstruation-regularity"
* item[3].item[0].item[1].text = "Менструации регулярные"
* item[3].item[0].item[1].answer[0].valueBoolean = false
* item[3].item[0].item[2].linkId = "regular-cycle-duration"
* item[3].item[0].item[2].text = "Длительность цикла (дней)"
* item[3].item[0].item[2].answer[0].valueInteger = 1
* item[3].item[0].item[3].linkId = "regular-menstruation-painfulness"
* item[3].item[0].item[3].text = "Болезненность менструаций"
* item[3].item[0].item[3].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-menstruation-painfulness-cs"
* item[3].item[0].item[3].answer[0].valueCoding.code = #scrn-0004-00001
* item[3].item[0].item[3].answer[0].valueCoding.display = "Болезненный"
* item[3].item[0].item[4].linkId = "regular-menstruation-abundance"
* item[3].item[0].item[4].text = "Обильность менструаций"
* item[3].item[0].item[4].answer[0].valueCoding.system = $sct
* item[3].item[0].item[4].answer[0].valueCoding.code = #386692008
* item[3].item[0].item[5].linkId = "regular-menstruation-onset-after-days"
* item[3].item[0].item[5].text = "После скольких дней наступает менструация"
* item[3].item[0].item[5].answer[0].valueInteger = 1
* item[3].item[1].linkId = "irregular-menstruation"
* item[3].item[1].text = "Характер при обследовании (нерегулярные)"
* item[3].item[1].item[0].linkId = "irregular-menstruation-start-age"
* item[3].item[1].item[0].text = "Возраст начала менструаций (нерегулярные)"
* item[3].item[1].item[0].answer[0].valueInteger = 0
* item[3].item[1].item[1].linkId = "irregular-menstruation-regularity"
* item[3].item[1].item[1].text = "Менструации регулярные"
* item[3].item[1].item[1].answer[0].valueBoolean = false
* item[3].item[1].item[2].linkId = "irregular-cycle-duration"
* item[3].item[1].item[2].text = "Длительность цикла (дней)"
* item[3].item[1].item[2].answer[0].valueInteger = 1
* item[3].item[1].item[3].linkId = "irregular-menstruation-painfulness"
* item[3].item[1].item[3].text = "Болезненность менструаций"
* item[3].item[1].item[3].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-menstruation-painfulness-cs"
* item[3].item[1].item[3].answer[0].valueCoding.code = #scrn-0004-00002
* item[3].item[1].item[3].answer[0].valueCoding.display = "Безболезненный"
* item[3].item[1].item[4].linkId = "irregular-menstruation-abundance"
* item[3].item[1].item[4].text = "Обильность менструаций"
* item[3].item[1].item[4].answer[0].valueCoding.system = $sct
* item[3].item[1].item[4].answer[0].valueCoding.code = #308550003
* item[3].item[1].item[5].linkId = "irregular-menstruation-onset-after-days"
* item[3].item[1].item[5].text = "После скольких дней наступает менструация"
* item[3].item[1].item[5].answer[0].valueInteger = 1
* item[3].item[2].linkId = "marital-status"
* item[3].item[2].text = "Статус брака"
* item[3].item[2].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-marital-status-cs"
* item[3].item[2].answer[0].valueCoding.code = #scrn-0035-00001
* item[3].item[2].answer[0].valueCoding.display = "I"
* item[3].item[3].linkId = "marriage-registration-status"
* item[3].item[3].text = "Статус регистрации брака"
* item[3].item[3].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-marriage-registration-status-cs"
* item[3].item[3].answer[0].valueCoding.code = #scrn-0036-00001
* item[3].item[3].answer[0].valueCoding.display = "Зарегистрирован"
* item[3].item[4].linkId = "sexual-debut-age"
* item[3].item[4].text = "Возраст начала половой жизни"
* item[3].item[4].answer[0].valueInteger = 1
* item[3].item[5].linkId = "last-menstrual-period-date"
* item[3].item[5].text = "Дата последней менструации"
* item[3].item[5].answer[0].valueDate = 2026-01-21
* item[3].item[6].linkId = "cycle-day-at-exam"
* item[3].item[6].text = "День менструального цикла на момент осмотра"
* item[3].item[6].answer[0].valueInteger = 1
* item[4].linkId = "reproductive-function"
* item[4].text = "Репродуктивная функция"
* item[4].item[0].linkId = "total-pregnancies"
* item[4].item[0].text = "Общее количество беременностей"
* item[4].item[0].answer[0].valueInteger = 1
* item[4].item[1].linkId = "pregnancy-outcome-types"
* item[4].item[1].text = "Типы исходов беременностей"
* item[4].item[1].answer[0].valueCoding.system = $sct
* item[4].item[1].answer[0].valueCoding.code = #6383007
* item[4].item[1].answer[1].valueCoding.system = $sct
* item[4].item[1].answer[1].valueCoding.code = #34801009
* item[4].item[1].answer[2].valueCoding.system = $sct
* item[4].item[1].answer[2].valueCoding.code = #17369002
* item[4].item[2].linkId = "living-children-count"
* item[4].item[2].text = "Количество живых детей"
* item[4].item[2].answer[0].valueInteger = 1
* item[4].item[3].linkId = "deceased-children-count"
* item[4].item[3].text = "Количество погибших детей"
* item[4].item[3].answer[0].valueInteger = 1
* item[4].item[4].linkId = "pregnancy-abortion-complications"
* item[4].item[4].text = "Осложнения после беременности/абортов"
* item[4].item[4].answer[0].valueCoding.system = $sct
* item[4].item[4].answer[0].valueCoding.code = #285409006
* item[4].item[4].answer[1].valueCoding.system = $sct
* item[4].item[4].answer[1].valueCoding.code = #17369002
* item[4].item[5].linkId = "gynecological-diseases-history"
* item[4].item[5].text = "Гинекологические заболевания в анамнезе"
* item[4].item[5].answer[0].valueCoding.system = $sct
* item[4].item[5].answer[0].valueCoding.code = #78623009
* item[4].item[5].answer[1].valueCoding.system = $sct
* item[4].item[5].answer[1].valueCoding.code = #95315005
* item[4].item[5].answer[2].valueCoding.system = $sct
* item[4].item[5].answer[2].valueCoding.code = #386804004
* item[4].item[5].answer[3].valueCoding.system = $sct
* item[4].item[5].answer[3].valueCoding.code = #30800001
* item[5].linkId = "surgical-procedure"
* item[5].text = "Гинекологические операции"
* item[5].item[0].linkId = "hysterosalpingography-1"
* item[5].item[0].text = "Гистеросальпингография"
* item[5].item[0].answer[0].valueBoolean = true
* item[5].item[1].linkId = "hysterosalpingography-1-comment"
* item[5].item[1].text = "Гистеросальпингография (комментарий)"
* item[5].item[1].answer[0].valueString = "1"
* item[5].item[2].linkId = "diagnostic-curettage"
* item[5].item[2].text = "Диагностическое выскабливание"
* item[5].item[2].answer[0].valueBoolean = true
* item[5].item[3].linkId = "diagnostic-curettage-comment"
* item[5].item[3].text = "Диагностическое выскабливание (комментарий)"
* item[5].item[3].answer[0].valueString = "1"
* item[5].item[4].linkId = "cervical-biopsy-history"
* item[5].item[4].text = "Биопсия шейки матки"
* item[5].item[4].answer[0].valueBoolean = true
* item[5].item[5].linkId = "cervical-biopsy-history-comment"
* item[5].item[5].text = "Биопсия шейки матки (комментарий)"
* item[5].item[5].answer[0].valueString = "1"
* item[5].item[6].linkId = "cervical-conization-history"
* item[5].item[6].text = "Конизация шейки матки"
* item[5].item[6].answer[0].valueBoolean = true
* item[5].item[7].linkId = "cervical-conization-history-comment"
* item[5].item[7].text = "Конизация шейки матки (комментарий)"
* item[5].item[7].answer[0].valueString = "1"
* item[5].item[8].linkId = "cervical-amputation-history"
* item[5].item[8].text = "Ампутация шейки матки"
* item[5].item[8].answer[0].valueBoolean = true
* item[5].item[9].linkId = "cervical-amputation-history-comment"
* item[5].item[9].text = "Ампутация шейки матки (комментарий)"
* item[5].item[9].answer[0].valueString = "1"
* item[5].item[10].linkId = "cervical-polyp-removal"
* item[5].item[10].text = "Удаление полипа шейки матки"
* item[5].item[10].answer[0].valueBoolean = true
* item[5].item[11].linkId = "cervical-polyp-removal-comment"
* item[5].item[11].text = "Удаление полипа шейки матки (комментарий)"
* item[5].item[11].answer[0].valueString = "1"
* item[5].item[12].linkId = "endometrial-polyp-removal"
* item[5].item[12].text = "Удаление полипа эндометрия (тела матки)"
* item[5].item[12].answer[0].valueBoolean = true
* item[5].item[13].linkId = "endometrial-polyp-removal-comment"
* item[5].item[13].text = "Удаление полипа эндометрия (тела матки) (комментарий)"
* item[5].item[13].answer[0].valueString = "1"
* item[5].item[14].linkId = "vaginal-plastic-surgery"
* item[5].item[14].text = "Пластика влагалища"
* item[5].item[14].answer[0].valueBoolean = true
* item[5].item[15].linkId = "vaginal-plastic-surgery-comment"
* item[5].item[15].text = "Пластика влагалища (комментарий)"
* item[5].item[15].answer[0].valueString = "1"
* item[5].item[16].linkId = "laparotomy"
* item[5].item[16].text = "Лапаротомия (разрез брюшной стенки)"
* item[5].item[16].answer[0].valueBoolean = true
* item[5].item[17].linkId = "laparotomy-comment"
* item[5].item[17].text = "Лапаротомия (разрез брюшной стенки) (комментарий)"
* item[5].item[17].answer[0].valueString = "1"
* item[5].item[18].linkId = "midline-laparotomy"
* item[5].item[18].text = "Срединная лапаротомия (пояснение к пункту выше)"
* item[5].item[18].answer[0].valueBoolean = true
* item[5].item[19].linkId = "midline-laparotomy-comment"
* item[5].item[19].text = "Срединная лапаротомия (пояснение к пункту выше) (комментарий)"
* item[5].item[19].answer[0].valueString = "1"
* item[5].item[20].linkId = "pfannenstiel-incision"
* item[5].item[20].text = "Разрез по Пфанненштилю"
* item[5].item[20].answer[0].valueBoolean = true
* item[5].item[21].linkId = "pfannenstiel-incision-comment"
* item[5].item[21].text = "Разрез по Пфанненштилю (комментарий)"
* item[5].item[21].answer[0].valueString = "1"
* item[5].item[22].linkId = "joel-cohen-incision"
* item[5].item[22].text = "Разрез по Джоэлю-Кохену"
* item[5].item[22].answer[0].valueBoolean = true
* item[5].item[23].linkId = "joel-cohen-incision-comment"
* item[5].item[23].text = "Разрез по Джоэлю-Кохену (комментарий)"
* item[5].item[23].answer[0].valueString = "1"
* item[5].item[24].linkId = "laparoscopy"
* item[5].item[24].text = "Лапароскопия"
* item[5].item[24].answer[0].valueBoolean = true
* item[5].item[25].linkId = "laparoscopy-comment"
* item[5].item[25].text = "Лапароскопия (комментарий)"
* item[5].item[25].answer[0].valueString = "1"
* item[5].item[26].linkId = "myomectomy"
* item[5].item[26].text = "Миомэктомия (удаление миомы матки)"
* item[5].item[26].answer[0].valueBoolean = true
* item[5].item[27].linkId = "myomectomy-comment"
* item[5].item[27].text = "Миомэктомия (удаление миомы матки) (комментарий)"
* item[5].item[27].answer[0].valueString = "1"
* item[5].item[28].linkId = "salpingectomy"
* item[5].item[28].text = "Удаление маточной трубы"
* item[5].item[28].answer[0].valueBoolean = true
* item[5].item[29].linkId = "salpingectomy-comment"
* item[5].item[29].text = "Удаление маточной трубы (комментарий)"
* item[5].item[29].answer[0].valueString = "1"
* item[5].item[30].linkId = "salpingotomy"
* item[5].item[30].text = "Вскрытие маточной трубы"
* item[5].item[30].answer[0].valueBoolean = true
* item[5].item[31].linkId = "salpingotomy-comment"
* item[5].item[31].text = "Вскрытие маточной трубы (комментарий)"
* item[5].item[31].answer[0].valueString = "1"
* item[5].item[32].linkId = "cyst-removal"
* item[5].item[32].text = "Удаление кисты"
* item[5].item[32].answer[0].valueBoolean = true
* item[5].item[33].linkId = "cyst-removal-comment"
* item[5].item[33].text = "Удаление кисты (комментарий)"
* item[5].item[33].answer[0].valueString = "1"
* item[5].item[34].linkId = "oophorectomy"
* item[5].item[34].text = "Резекция яичника"
* item[5].item[34].answer[0].valueBoolean = true
* item[5].item[35].linkId = "oophorectomy-comment"
* item[5].item[35].text = "Резекция яичника (комментарий)"
* item[5].item[35].answer[0].valueString = "1"
* item[5].item[36].linkId = "adnexectomy"
* item[5].item[36].text = "Удаление придатков матки"
* item[5].item[36].answer[0].valueBoolean = true
* item[5].item[37].linkId = "adnexectomy-comment"
* item[5].item[37].text = "Удаление придатков матки (комментарий)"
* item[5].item[37].answer[0].valueString = "1"
* item[5].item[38].linkId = "subtotal-hysterectomy"
* item[5].item[38].text = "Субтотальная гистерэктомия"
* item[5].item[38].answer[0].valueBoolean = true
* item[5].item[39].linkId = "subtotal-hysterectomy-comment"
* item[5].item[39].text = "Субтотальная гистерэктомия (комментарий)"
* item[5].item[39].answer[0].valueString = "1"
* item[5].item[40].linkId = "total-hysterectomy"
* item[5].item[40].text = "Тотальная (полная) гистерэктомия"
* item[5].item[40].answer[0].valueBoolean = true
* item[5].item[41].linkId = "total-hysterectomy-comment"
* item[5].item[41].text = "Тотальная (полная) гистерэктомия (комментарий)"
* item[5].item[41].answer[0].valueString = "1"
* item[5].item[42].linkId = "with-adnexa"
* item[5].item[42].text = "С придатками"
* item[5].item[42].answer[0].valueBoolean = true
* item[5].item[43].linkId = "with-adnexa-comment"
* item[5].item[43].text = "С придатками (комментарий)"
* item[5].item[43].answer[0].valueString = "1"
* item[5].item[44].linkId = "without-adnexa"
* item[5].item[44].text = "Без придатков"
* item[5].item[44].answer[0].valueBoolean = true
* item[5].item[45].linkId = "without-adnexa-comment"
* item[5].item[45].text = "Без придатков (комментарий)"
* item[5].item[45].answer[0].valueString = "1"
* item[6].linkId = "contraception"
* item[6].text = "Методы контрацепции"
* item[6].item[0].linkId = "contraception-condom"
* item[6].item[0].text = "Презерватив"
* item[6].item[0].answer[0].valueBoolean = true
* item[6].item[1].linkId = "contraception-coc"
* item[6].item[1].text = "Комбинированные оральные контрацептивы (КОК)"
* item[6].item[1].answer[0].valueBoolean = true
* item[6].item[2].linkId = "contraception-iud-spiral"
* item[6].item[2].text = "Внутриматочная контрацепция (спираль)"
* item[6].item[2].answer[0].valueBoolean = true
* item[6].item[3].linkId = "contraception-vaginal-suppositories"
* item[6].item[3].text = "Свечи (вагинальные суппозитории)"
* item[6].item[3].answer[0].valueBoolean = true
* item[6].item[4].linkId = "contraception-withdrawal"
* item[6].item[4].text = "Прерванный половой акт"
* item[6].item[4].answer[0].valueBoolean = true
* item[6].item[5].linkId = "contraception-surgical-sterilization"
* item[6].item[5].text = "Добровольная хирургическая стерилизация"
* item[6].item[5].answer[0].valueBoolean = true
* item[6].item[6].linkId = "contraception-intrauterine"
* item[6].item[6].text = "Внутриматочные контрацептивы"
* item[6].item[6].answer[0].valueBoolean = true
* item[6].item[7].linkId = "contraception-natural"
* item[6].item[7].text = "Естественные методы"
* item[6].item[7].answer[0].valueBoolean = true
* item[6].item[8].linkId = "contraception-other"
* item[6].item[8].text = "Другое"
* item[6].item[8].answer[0].valueBoolean = true
* item[6].item[9].linkId = "contraception-other-comment"
* item[6].item[9].text = "Другие (комментарий)"
* item[6].item[9].answer[0].valueString = "1"
* item[7].linkId = "general-obesity"
* item[7].text = "Общее состояние и степень ожирения"
* item[7].item[0].linkId = "general-condition"
* item[7].item[0].text = "Общее состояние"
* item[7].item[0].answer[0].valueCoding.system = $sct
* item[7].item[0].answer[0].valueCoding.code = #6736007
* item[7].item[1].linkId = "obesity-degree"
* item[7].item[1].text = "Степень ожирения"
* item[7].item[1].answer[0].valueCoding.system = $sct
* item[7].item[1].answer[0].valueCoding.code = #162864005
* item[8].linkId = "hirsutism-general-exam"
* item[8].text = "Степень гирсутизма и дополнительные данные общего осмотра"
* item[8].item[0].linkId = "hirsutism-face"
* item[8].item[0].text = "На лице"
* item[8].item[0].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-hirsutism-face-cs"
* item[8].item[0].answer[0].valueCoding.code = #scrn-0010-00002
* item[8].item[0].answer[0].valueCoding.display = "Пушковые волосы"
* item[8].item[0].answer[1].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-hirsutism-face-cs"
* item[8].item[0].answer[1].valueCoding.code = #scrn-0010-00001
* item[8].item[0].answer[1].valueCoding.display = "Редкие волосы на лице"
* item[8].item[0].answer[2].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-hirsutism-face-cs"
* item[8].item[0].answer[2].valueCoding.code = #scrn-0010-00004
* item[8].item[0].answer[2].valueCoding.display = "Акне на лице"
* item[8].item[1].linkId = "hirsutism-thighs"
* item[8].item[1].text = "На бедрах"
* item[8].item[1].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-hirsutism-thigh-cs"
* item[8].item[1].answer[0].valueCoding.code = #scrn-0011-00001
* item[8].item[1].answer[0].valueCoding.display = "Редкие волосы на бедрах"
* item[8].item[1].answer[1].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-hirsutism-thigh-cs"
* item[8].item[1].answer[1].valueCoding.code = #scrn-0011-00002
* item[8].item[1].answer[1].valueCoding.display = "Обильный рост волос на бедрах"
* item[8].item[2].linkId = "hirsutism-abdomen"
* item[8].item[2].text = "Другое / на животе"
* item[8].item[2].answer[0].valueCoding.system = $sct
* item[8].item[2].answer[0].valueCoding.code = #251823004
* item[8].item[2].answer[1].valueCoding.system = $sct
* item[8].item[2].answer[1].valueCoding.code = #201066002
* item[8].item[3].linkId = "stretch-marks-color"
* item[8].item[3].text = "Цвет растяжек"
* item[8].item[3].answer[0].valueString = "1"
* item[8].item[4].linkId = "stretch-marks-count"
* item[8].item[4].text = "Кол-во растяжек"
* item[8].item[4].answer[0].valueInteger = 1
* item[8].item[5].linkId = "stretch-marks-location"
* item[8].item[5].text = "Локализация растяжек"
* item[8].item[5].answer[0].valueString = "1"
* item[8].item[6].linkId = "thyroid-assessment"
* item[8].item[6].text = "Оценка щитовидной железы"
* item[8].item[6].answer[0].valueBoolean = true
* item[8].item[7].linkId = "thyroid-enlargement-degree"
* item[8].item[7].text = "Степень увеличения"
* item[8].item[7].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-thyroid-enlargement-degree-cs"
* item[8].item[7].answer[0].valueCoding.code = #scrn-0013-00001
* item[8].item[7].answer[0].valueCoding.display = "Диффузное увеличение"
* item[8].item[7].answer[1].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-thyroid-enlargement-degree-cs"
* item[8].item[7].answer[1].valueCoding.code = #scrn-0013-00002
* item[8].item[7].answer[1].valueCoding.display = "Увеличение I степени"
* item[8].item[8].linkId = "breast-assessment"
* item[8].item[8].text = "Оценка молочных желез"
* item[8].item[8].answer[0].valueCoding.system = $sct
* item[8].item[8].answer[0].valueCoding.code = #6703006
* item[8].item[8].answer[1].valueCoding.system = $sct
* item[8].item[8].answer[1].valueCoding.code = #20897003
* item[8].item[9].linkId = "breast-palpation-assessment"
* item[8].item[9].text = "При пальпации"
* item[8].item[9].answer[0].valueCoding.system = $sct
* item[8].item[9].answer[0].valueCoding.code = #299976000
* item[8].item[9].answer[1].valueCoding.system = $sct
* item[8].item[9].answer[1].valueCoding.code = #53430007
* item[8].item[10].linkId = "axillary-nodes-palpable"
* item[8].item[10].text = "Подмышечные лимфатические узлы определяются при пальпации"
* item[8].item[10].answer[0].valueBoolean = true
* item[8].item[11].linkId = "nipple-hair"
* item[8].item[11].text = "Оволосение сосков молочных желез"
* item[8].item[11].answer[0].valueBoolean = true
* item[8].item[12].linkId = "nipple-discharge-present"
* item[8].item[12].text = "Выделения из сосков"
* item[8].item[12].answer[0].valueBoolean = true
* item[8].item[13].linkId = "nipple-discharge-comment"
* item[8].item[13].text = "Выделения из сосков (комментарий)"
* item[8].item[13].answer[0].valueString = "1"
* item[8].item[14].linkId = "liver-spleen-palpable"
* item[8].item[14].text = "Печень/селезенка пальпируются?"
* item[8].item[14].answer[0].valueBoolean = true
* item[8].item[15].linkId = "urination"
* item[8].item[15].text = "Мочеиспускание"
* item[8].item[15].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-urination-characteristic-cs"
* item[8].item[15].answer[0].valueCoding.code = #scrn-0016-00002
* item[8].item[15].answer[0].valueCoding.display = "С резкими болями"
* item[8].item[16].linkId = "urination-times-per-day"
* item[8].item[16].text = "Кол-во раз в сутки"
* item[8].item[16].answer[0].valueInteger = 1
* item[8].item[17].linkId = "defecation-times-per-day"
* item[8].item[17].text = "Дефекация (кол-во раз в сутки)"
* item[8].item[17].answer[0].valueInteger = 1
* item[8].item[18].linkId = "constipation-tendency"
* item[8].item[18].text = "Склонность к запорам"
* item[8].item[18].answer[0].valueBoolean = true
* item[8].item[19].linkId = "leg-varicose-veins"
* item[8].item[19].text = "Варикозное расширение вен ног"
* item[8].item[19].answer[0].valueBoolean = true
* item[9].linkId = "gynecological-status"
* item[9].text = "Гинекологическое состояние"
* item[9].item[0].linkId = "external-genitalia-normal"
* item[9].item[0].text = "Развитие наружных половых органов"
* item[9].item[0].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-external-genitalia-development-cs"
* item[9].item[0].answer[0].valueCoding.code = #scrn-0062-00001
* item[9].item[0].answer[0].valueCoding.display = "Нормальное развитие"
* item[9].item[1].linkId = "genital-slit-closed"
* item[9].item[1].text = "Состояние половой щели"
* item[9].item[1].answer[0].valueCoding.system = $sct
* item[9].item[1].answer[0].valueCoding.code = #434851000124108
* item[9].item[2].linkId = "vaginal-mucosa-pink"
* item[9].item[2].text = "Состояние слизистой оболочки влагалища"
* item[9].item[2].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-vaginal-mucosa-condition-cs"
* item[9].item[2].answer[0].valueCoding.code = #scrn-0064-00002
* item[9].item[2].answer[0].valueCoding.display = "Покрасневшая"
* item[9].item[3].linkId = "vaginal-os-punctate"
* item[9].item[3].text = "Форма зева влагалища"
* item[9].item[3].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-vaginal-os-shape-cs"
* item[9].item[3].answer[0].valueCoding.code = #scrn-0065-00002
* item[9].item[3].answer[0].valueCoding.display = "Щелевидный"
* item[9].item[4].linkId = "vagina-parous"
* item[9].item[4].text = "Состояние влагалища с учётом паритета"
* item[9].item[4].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-vaginal-parity-status-cs"
* item[9].item[4].answer[0].valueCoding.code = #scrn-0066-00001
* item[9].item[4].answer[0].valueCoding.display = "Влагалище нерожавшей женщины"
* item[9].item[5].linkId = "external-cervical-os-closed"
* item[9].item[5].text = "Состояние наружного зева шейки матки"
* item[9].item[5].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-external-cervical-os-state-cs"
* item[9].item[5].answer[0].valueCoding.code = #scrn-0067-00001
* item[9].item[5].answer[0].valueCoding.display = "Закрыт"
* item[9].item[6].linkId = "cervicitis-absent"
* item[9].item[6].text = "Наличие признаков цервицита"
* item[9].item[6].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-cervicitis-status-cs"
* item[9].item[6].answer[0].valueCoding.code = #scrn-0068-00001
* item[9].item[6].answer[0].valueCoding.display = "Признаков цервицита нет"
* item[9].item[7].linkId = "hair-growth"
* item[9].item[7].text = "Оволосение"
* item[9].item[7].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-pubic-hair-pattern-cs"
* item[9].item[7].answer[0].valueCoding.code = #scrn-0017-00001
* item[9].item[7].answer[0].valueCoding.display = "По женскому типу"
* item[9].item[7].answer[1].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-pubic-hair-pattern-cs"
* item[9].item[7].answer[1].valueCoding.code = #scrn-0017-00002
* item[9].item[7].answer[1].valueCoding.display = "По смешанному типу"
* item[9].item[8].linkId = "tvme"
* item[9].item[8].text = "ТВМЕ / опущение стенок влагалища"
* item[9].item[8].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-vaginal-wall-prolapse-cs"
* item[9].item[8].answer[0].valueCoding.code = #scrn-0018-00001
* item[9].item[8].answer[0].valueCoding.display = "Опущение стенок влагалища"
* item[9].item[8].answer[1].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-vaginal-wall-prolapse-cs"
* item[9].item[8].answer[1].valueCoding.code = #scrn-0018-00002
* item[9].item[8].answer[1].valueCoding.display = "Цистоцеле (опущение мочевого пузыря во влагалище)"
* item[9].item[9].linkId = "uterus-vagina-visual-condition"
* item[9].item[9].text = "Состояние матки и влагалища (осмотр)"
* item[9].item[9].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-uterus-vagina-visual-condition-cs"
* item[9].item[9].answer[0].valueCoding.code = #scrn-0026-00003
* item[9].item[9].answer[0].valueCoding.display = "Признаки недоразвития половых органов"
* item[9].item[9].answer[1].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-uterus-vagina-visual-condition-cs"
* item[9].item[9].answer[1].valueCoding.code = #scrn-0026-00002
* item[9].item[9].answer[1].valueCoding.display = "Полное выпадение матки"
* item[9].item[9].answer[2].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-uterus-vagina-visual-condition-cs"
* item[9].item[9].answer[2].valueCoding.code = #scrn-0026-00007
* item[9].item[9].answer[2].valueCoding.display = "Удлинение шейки матки"
* item[9].item[9].answer[3].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-uterus-vagina-visual-condition-cs"
* item[9].item[9].answer[3].valueCoding.code = #scrn-0026-00005
* item[9].item[9].answer[3].valueCoding.display = "Старые разрывы половых органов"
* item[9].item[10].linkId = "vaginal-discharge"
* item[9].item[10].text = "Выделения из влагалища"
* item[9].item[10].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-vaginal-discharge-type-cs"
* item[9].item[10].answer[0].valueCoding.code = #scrn-0019-00009
* item[9].item[10].answer[0].valueCoding.display = "Другое"
* item[9].item[10].answer[1].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-vaginal-discharge-type-cs"
* item[9].item[10].answer[1].valueCoding.code = #scrn-0019-00002
* item[9].item[10].answer[1].valueCoding.display = "Мутные"
* item[9].item[10].answer[2].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-vaginal-discharge-type-cs"
* item[9].item[10].answer[2].valueCoding.code = #scrn-0019-00004
* item[9].item[10].answer[2].valueCoding.display = "Желтая жидкость с кровью"
* item[9].item[11].linkId = "vaginal-discharge-comment"
* item[9].item[11].text = "Выделения из влагалища (комментарий)"
* item[9].item[11].answer[0].valueString = "1"
* item[9].item[12].linkId = "vaginal-discharge-quantity"
* item[9].item[12].text = "Кол-во"
* item[9].item[12].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-vaginal-discharge-amount-cs"
* item[9].item[12].answer[0].valueCoding.code = #scrn-0020-00003
* item[9].item[12].answer[0].valueCoding.display = "Норма"
* item[9].item[13].linkId = "vaginal-discharge-odor"
* item[9].item[13].text = "Запах"
* item[9].item[13].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-vaginal-discharge-odor-cs"
* item[9].item[13].answer[0].valueCoding.code = #scrn-0021-00001
* item[9].item[13].answer[0].valueCoding.display = "Запах рыбы"
* item[9].item[14].linkId = "cervix-condition"
* item[9].item[14].text = "Шейка матки"
* item[9].item[14].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-cervix-condition-cs"
* item[9].item[14].answer[0].valueCoding.code = #scrn-0022-00001
* item[9].item[14].answer[0].valueCoding.display = "С наличием старых разрывов Деформированная шейка"
* item[9].item[15].linkId = "cervix-size"
* item[9].item[15].text = "Размер шейки матки"
* item[9].item[15].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-cervix-size-cs"
* item[9].item[15].answer[0].valueCoding.code = #scrn-0023-00002
* item[9].item[15].answer[0].valueCoding.display = "Увеличенный размер"
* item[9].item[16].linkId = "pupil-sign-present"
* item[9].item[16].text = "Симптом «зрачка» присутствует"
* item[9].item[16].answer[0].valueBoolean = true
* item[9].item[17].linkId = "cervical-mucus-stretchability"
* item[9].item[17].text = "Симптом растяжимости слизистой шейки"
* item[9].item[17].answer[0].valueBoolean = true
* item[9].item[18].linkId = "cervix-length"
* item[9].item[18].text = "Длина шейки матки"
* item[9].item[18].answer[0].valueDecimal = 1
* item[10].linkId = "uterine-body"
* item[10].text = "Тело матки и придатки"
* item[10].item[0].linkId = "uterus-size-normal"
* item[10].item[0].text = "Размер матки нормальный"
* item[10].item[0].answer[0].valueBoolean = true
* item[10].item[1].linkId = "uterus-size-enlarged"
* item[10].item[1].text = "Увеличенный размер"
* item[10].item[1].answer[0].valueBoolean = true
* item[10].item[2].linkId = "uterus-size-below-normal"
* item[10].item[2].text = "Меньше нормы"
* item[10].item[2].answer[0].valueBoolean = true
* item[10].item[3].linkId = "uterus-painful"
* item[10].item[3].text = "Болезненная"
* item[10].item[3].answer[0].valueBoolean = true
* item[10].item[4].linkId = "uterus-dense"
* item[10].item[4].text = "Плотная"
* item[10].item[4].answer[0].valueBoolean = true
* item[10].item[5].linkId = "left-adnexa-enlarged"
* item[10].item[5].text = "Левый придаток увеличен"
* item[10].item[5].answer[0].valueBoolean = true
* item[10].item[6].linkId = "left-adnexa-size-cm"
* item[10].item[6].text = "Размер левого придатка в см."
* item[10].item[6].answer[0].valueDecimal = 1
* item[10].item[7].linkId = "right-adnexa-defined"
* item[10].item[7].text = "Правый придаток определяется"
* item[10].item[7].answer[0].valueBoolean = true
* item[10].item[8].linkId = "right-adnexa-size-cm"
* item[10].item[8].text = "Размер правого придатка в см."
* item[10].item[8].answer[0].valueDecimal = 0
* item[10].item[9].linkId = "uterine-vaults"
* item[10].item[9].text = "Своды матки"
* item[10].item[9].answer[0].valueCoding.system = "https://terminology.dhp.uz/fhir/integrations/CodeSystem/screening-uterine-vault-status-cs"
* item[10].item[9].answer[0].valueCoding.code = #scrn-0024-00001
* item[10].item[9].answer[0].valueCoding.display = "Своды матки симметричные"
