// Source: Questionnaire-breast-risk.json
Instance: ScreeningBreastRiskQuestionnaire
InstanceOf: UZCoreQuestionnaire
Usage: #definition
Title: "Screening Breast Risk Questionnaire"
Description: "Questionnaire used by Screening to assess breast cancer risk."
* id = "screening-breast-risk"
* language = #uz
* url = "https://dhp.uz/fhir/integrations/Questionnaire/screening-breast-risk"
* identifier[0].system = "https://dhp.uz/fhir/integrations/sid/screening/questionnaire-id"
* identifier[0].value = "1"
* identifier[1].system = "https://dhp.uz/fhir/integrations/sid/screening/questionnaire-code"
* identifier[1].value = "RMJ"
* version = "1.0.1"
* status = #active
* useContext[0].code = $usage-context-type#program
* useContext[0].valueCodeableConcept = $integration-area#screening
* name = "ScreeningBreastRiskQuestionnaire"
* title = "Ko'krak bezi so'rovnomasi"
* description = "Screening tizimida ko‘krak bezi saratoni xavfini baholash uchun so‘rovnoma."
* title.extension[0].extension[0].url = "lang"
* title.extension[0].extension[0].valueCode = #ru
* title.extension[0].extension[1].url = "content"
* title.extension[0].extension[1].valueString = "Опросник по молочной железе"
* title.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* subjectType[0] = #Patient
* item[0].linkId = "118"
* item[0].text = "Sizda ilgari onkologik kasalliklar aniqlanganmi? (masalan, tuxumdon o‘smalari, limfomalar)"
* item[0].text.extension[0].extension[0].url = "lang"
* item[0].text.extension[0].extension[0].valueCode = #ru
* item[0].text.extension[0].extension[1].url = "content"
* item[0].text.extension[0].extension[1].valueString = "Были ли у вас ранее диагностированы онкологические болезни? (например, опухоли, яичников, лимфомы)"
* item[0].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[0].type = #boolean
* item[0].repeats = false
* item[1].linkId = "119"
* item[1].text = "Birinchi hayz ko‘rish necha yoshda bo‘lgan?"
* item[1].text.extension[0].extension[0].url = "lang"
* item[1].text.extension[0].extension[0].valueCode = #ru
* item[1].text.extension[0].extension[1].url = "content"
* item[1].text.extension[0].extension[1].valueString = "В каком возрасте была первая менструация?"
* item[1].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[1].type = #coding
* item[1].repeats = false
* item[1].answerConstraint = #optionsOnly
* item[1].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-breast-menarche-age-vs"
* item[2].linkId = "34"
* item[2].text = "Ko‘krak bezi zichligini qanday baholaysiz?"
* item[2].text.extension[0].extension[0].url = "lang"
* item[2].text.extension[0].extension[0].valueCode = #ru
* item[2].text.extension[0].extension[1].url = "content"
* item[2].text.extension[0].extension[1].valueString = "Как вы оцениваете плотность своей груди?"
* item[2].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[2].type = #coding
* item[2].repeats = false
* item[2].answerConstraint = #optionsOnly
* item[2].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-breast-self-assessed-density-vs"
* item[3].linkId = "117"
* item[3].text = "Birinchi darajali qarindoshlarda (ona, opa-singil, qiz) ko‘krak bezi saratoni bilan kasallanish holatlari bormi?"
* item[3].text.extension[0].extension[0].url = "lang"
* item[3].text.extension[0].extension[0].valueCode = #ru
* item[3].text.extension[0].extension[1].url = "content"
* item[3].text.extension[0].extension[1].valueString = "Есть ли случаи рака молочной железы у родственников первой линии (мать, сестра, дочь)?"
* item[3].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[3].type = #boolean
* item[3].repeats = false
* item[4].linkId = "120"
* item[4].text = "Oxirgi marta necha yoshda hayz ko‘rgan?"
* item[4].text.extension[0].extension[0].url = "lang"
* item[4].text.extension[0].extension[0].valueCode = #ru
* item[4].text.extension[0].extension[1].url = "content"
* item[4].text.extension[0].extension[1].valueString = "В каком возрасте была последняя менструация?"
* item[4].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[4].type = #coding
* item[4].repeats = false
* item[4].answerConstraint = #optionsOnly
* item[4].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-breast-menopause-age-vs"
* item[5].linkId = "121"
* item[5].text = "Birinchi tug‘ruq necha yoshda bo‘lgan?"
* item[5].text.extension[0].extension[0].url = "lang"
* item[5].text.extension[0].extension[0].valueCode = #ru
* item[5].text.extension[0].extension[1].url = "content"
* item[5].text.extension[0].extension[1].valueString = "В каком возрасте были первые роды?"
* item[5].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[5].type = #coding
* item[5].repeats = false
* item[5].answerConstraint = #optionsOnly
* item[5].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-breast-first-birth-age-vs"
* item[6].linkId = "122"
* item[6].text = "Oxirgi bolangizni qancha vaqt emizgansiz?"
* item[6].text.extension[0].extension[0].url = "lang"
* item[6].text.extension[0].extension[0].valueCode = #ru
* item[6].text.extension[0].extension[1].url = "content"
* item[6].text.extension[0].extension[1].valueString = "Сколько времени вы кормили грудью последнего ребенка?"
* item[6].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[6].type = #coding
* item[6].repeats = false
* item[6].answerConstraint = #optionsOnly
* item[6].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-breast-breastfeeding-duration-vs"
* item[7].linkId = "123"
* item[7].text = "Oxirgi 3 oyda ko‘krak bezi yoki qo‘ltiq osti sohasida qattiqlashishni sezganmisiz?"
* item[7].text.extension[0].extension[0].url = "lang"
* item[7].text.extension[0].extension[0].valueCode = #ru
* item[7].text.extension[0].extension[1].url = "content"
* item[7].text.extension[0].extension[1].valueString = "Замечали ли вы уплотнения в груди или подмышечной области в последние 3 месяца?"
* item[7].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[7].type = #boolean
* item[7].repeats = false
* item[8].linkId = "124"
* item[8].text = "Sizda emizish bilan bog‘liq bo‘lmagan so‘rg‘ichdan ajralma kelganmi?"
* item[8].text.extension[0].extension[0].url = "lang"
* item[8].text.extension[0].extension[0].valueCode = #ru
* item[8].text.extension[0].extension[1].url = "content"
* item[8].text.extension[0].extension[1].valueString = "Были ли у вас выделения из соска, не связанные с кормлением?"
* item[8].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[8].type = #coding
* item[8].repeats = false
* item[8].answerConstraint = #optionsOnly
* item[8].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-breast-nipple-discharge-vs"
* item[9].linkId = "125"
* item[9].text = "Ko‘krak bezining ko‘rinishi (shakli, o‘lchami, terisining qattiqlashishi va qizarishi, so‘rg‘ichning ichiga tortilishi) o‘zgarganmi?"
* item[9].text.extension[0].extension[0].url = "lang"
* item[9].text.extension[0].extension[0].valueCode = #ru
* item[9].text.extension[0].extension[1].url = "content"
* item[9].text.extension[0].extension[1].valueString = "Изменился ли внешний вид груди (форма, размер,  уплотнение и покраснение кожи, втяжение соска)?"
* item[9].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[9].type = #coding
* item[9].repeats = false
* item[9].answerConstraint = #optionsOnly
* item[9].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-breast-appearance-change-vs"
* item[10].linkId = "126"
* item[10].text = "Gormonal dorilar (homiladorlikka qarshi, klimaks paytida gormonal tabletkalar) qabul qilganmisiz?"
* item[10].text.extension[0].extension[0].url = "lang"
* item[10].text.extension[0].extension[0].valueCode = #ru
* item[10].text.extension[0].extension[1].url = "content"
* item[10].text.extension[0].extension[1].valueString = "Принимали ли вы гормональные препараты  (противозачаточные, гормональные таблетки во время климакса)"
* item[10].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[10].type = #boolean
* item[10].repeats = false
* item[11].linkId = "statusRisk"
* item[11].text = "Hisoblangan ko‘krak bezi saratoni xavfi"
* item[11].text.extension[0].extension[0].url = "lang"
* item[11].text.extension[0].extension[0].valueCode = #ru
* item[11].text.extension[0].extension[1].url = "content"
* item[11].text.extension[0].extension[1].valueString = "Рассчитанный риск рака молочной железы"
* item[11].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[11].type = #coding
* item[11].repeats = false
* item[11].readOnly = true
* item[11].answerConstraint = #optionsOnly
* item[11].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-risk-level-vs"

// Source: Questionnaire-cervical-risk.json
Instance: ScreeningCervicalRiskQuestionnaire
InstanceOf: UZCoreQuestionnaire
Usage: #definition
Title: "Screening Cervical Risk Questionnaire"
Description: "Questionnaire used by Screening to assess cervical cancer risk."
* id = "screening-cervical-risk"
* language = #uz
* url = "https://dhp.uz/fhir/integrations/Questionnaire/screening-cervical-risk"
* identifier[0].system = "https://dhp.uz/fhir/integrations/sid/screening/questionnaire-id"
* identifier[0].value = "3"
* identifier[1].system = "https://dhp.uz/fhir/integrations/sid/screening/questionnaire-code"
* identifier[1].value = "RSHM"
* version = "1.0.1"
* status = #active
* useContext[0].code = $usage-context-type#program
* useContext[0].valueCodeableConcept = $integration-area#screening
* name = "ScreeningCervicalRiskQuestionnaire"
* title = "Bachadon bo'yni bo'yicha so'rovnoma"
* description = "Screening tizimida bachadon bo‘yni saratoni xavfini baholash uchun so‘rovnoma."
* title.extension[0].extension[0].url = "lang"
* title.extension[0].extension[0].valueCode = #ru
* title.extension[0].extension[1].url = "content"
* title.extension[0].extension[1].valueString = "Опросник по шейке матки"
* title.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* subjectType[0] = #Patient
* item[0].linkId = "35"
* item[0].text = "Ayollar jinsiy a’zolarida operatsiya qilinganmi?"
* item[0].text.extension[0].extension[0].url = "lang"
* item[0].text.extension[0].extension[0].valueCode = #ru
* item[0].text.extension[0].extension[1].url = "content"
* item[0].text.extension[0].extension[1].valueString = "Проводилась ли операция на женских половых органах?"
* item[0].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[0].type = #coding
* item[0].repeats = false
* item[0].answerConstraint = #optionsOnly
* item[0].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-cervical-previous-surgery-vs"
* item[1].linkId = "103"
* item[1].text = "OPV testi natijasi"
* item[1].text.extension[0].extension[0].url = "lang"
* item[1].text.extension[0].extension[0].valueCode = #ru
* item[1].text.extension[0].extension[1].url = "content"
* item[1].text.extension[0].extension[1].valueString = "Результат ВПЧ-теста"
* item[1].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[1].type = #coding
* item[1].repeats = false
* item[1].answerConstraint = #optionsOnly
* item[1].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-cervical-hpv-test-result-vs"
* item[2].linkId = "104"
* item[2].text = "PAP test natijalari g‘ayritabiiymi?"
* item[2].text.extension[0].extension[0].url = "lang"
* item[2].text.extension[0].extension[0].valueCode = #ru
* item[2].text.extension[0].extension[1].url = "content"
* item[2].text.extension[0].extension[1].valueString = "Результаты ПАП-теста аномальные?"
* item[2].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[2].type = #boolean
* item[2].repeats = false
* item[3].linkId = "105"
* item[3].text = "Oilaviy holatingiz"
* item[3].text.extension[0].extension[0].url = "lang"
* item[3].text.extension[0].extension[0].valueCode = #ru
* item[3].text.extension[0].extension[1].url = "content"
* item[3].text.extension[0].extension[1].valueString = "Ваше семейное положение"
* item[3].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[3].type = #coding
* item[3].repeats = false
* item[3].answerConstraint = #optionsOnly
* item[3].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-cervical-marital-status-vs"
* item[4].linkId = "106"
* item[4].text = "Siz necha yoshdan jinsiy hayotni boshlagansiz?"
* item[4].text.extension[0].extension[0].url = "lang"
* item[4].text.extension[0].extension[0].valueCode = #ru
* item[4].text.extension[0].extension[1].url = "content"
* item[4].text.extension[0].extension[1].valueString = "В каком возрасте вы начали половую жизнь?"
* item[4].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[4].type = #coding
* item[4].repeats = false
* item[4].answerConstraint = #optionsOnly
* item[4].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-cervical-sexual-debut-age-vs"
* item[5].linkId = "36"
* item[5].text = "Hozirgi vaqtda sizda bachadon bo‘yni saratoni aniqlanganmi?"
* item[5].text.extension[0].extension[0].url = "lang"
* item[5].text.extension[0].extension[0].valueCode = #ru
* item[5].text.extension[0].extension[1].url = "content"
* item[5].text.extension[0].extension[1].valueString = "Диагностирован ли у вас РШМ в данное время?"
* item[5].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[5].type = #boolean
* item[5].repeats = false
* item[6].linkId = "37"
* item[6].text = "Anamnezda bachadon bo‘yni saratoni bo‘lganmi?"
* item[6].text.extension[0].extension[0].url = "lang"
* item[6].text.extension[0].extension[0].valueCode = #ru
* item[6].text.extension[0].extension[1].url = "content"
* item[6].text.extension[0].extension[1].valueString = "Был ли у вас РШМ в анамнезе?"
* item[6].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[6].type = #boolean
* item[6].repeats = false
* item[7].linkId = "107"
* item[7].text = "Sizda nechta jinsiy sherik bo‘lgan?"
* item[7].text.extension[0].extension[0].url = "lang"
* item[7].text.extension[0].extension[0].valueCode = #ru
* item[7].text.extension[0].extension[1].url = "content"
* item[7].text.extension[0].extension[1].valueString = "Сколько сексуальных партнеров у вас было?"
* item[7].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[7].type = #coding
* item[7].repeats = false
* item[7].answerConstraint = #optionsOnly
* item[7].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-cervical-sexual-partner-count-vs"
* item[8].linkId = "41"
* item[8].text = "Siz hech OPV testidan o‘tganmisiz?"
* item[8].text.extension[0].extension[0].url = "lang"
* item[8].text.extension[0].extension[0].valueCode = #ru
* item[8].text.extension[0].extension[1].url = "content"
* item[8].text.extension[0].extension[1].valueString = "Проходили ли вы когда-либо тест на ВПЧ?"
* item[8].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[8].type = #boolean
* item[8].repeats = false
* item[9].linkId = "108"
* item[9].text = "Siz homilador bo‘lganmisiz? (jumladan, bola tushishi va abortlar)"
* item[9].text.extension[0].extension[0].url = "lang"
* item[9].text.extension[0].extension[0].valueCode = #ru
* item[9].text.extension[0].extension[1].url = "content"
* item[9].text.extension[0].extension[1].valueString = "Вы были беременны? (Включая выкидыши и аборты)"
* item[9].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[9].type = #coding
* item[9].repeats = false
* item[9].answerConstraint = #optionsOnly
* item[9].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-cervical-pregnancy-history-vs"
* item[10].linkId = "109"
* item[10].text = "Abort yoki bola tashlashlar soni"
* item[10].text.extension[0].extension[0].url = "lang"
* item[10].text.extension[0].extension[0].valueCode = #ru
* item[10].text.extension[0].extension[1].url = "content"
* item[10].text.extension[0].extension[1].valueString = "Кол-во абортов или выкидышей"
* item[10].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[10].type = #coding
* item[10].repeats = false
* item[10].answerConstraint = #optionsOnly
* item[10].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-cervical-abortion-count-vs"
* item[11].linkId = "110"
* item[11].text = "Chekasizmi?"
* item[11].text.extension[0].extension[0].url = "lang"
* item[11].text.extension[0].extension[0].valueCode = #ru
* item[11].text.extension[0].extension[1].url = "content"
* item[11].text.extension[0].extension[1].valueString = "Вы курите?"
* item[11].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[11].type = #coding
* item[11].repeats = false
* item[11].answerConstraint = #optionsOnly
* item[11].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-cervical-smoking-status-vs"
* item[12].linkId = "111"
* item[12].text = "Kontratsepsiya usullaridan foydalanasizmi?"
* item[12].text.extension[0].extension[0].url = "lang"
* item[12].text.extension[0].extension[0].valueCode = #ru
* item[12].text.extension[0].extension[1].url = "content"
* item[12].text.extension[0].extension[1].valueString = "Пользуетесь ли вы методами контрацепции?"
* item[12].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[12].type = #coding
* item[12].repeats = false
* item[12].answerConstraint = #optionsOnly
* item[12].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-cervical-contraception-method-vs"
* item[13].linkId = "112"
* item[13].text = "Sizda jinsiy yo‘l bilan yuqadigan kasalliklar bo‘lganmi?"
* item[13].text.extension[0].extension[0].url = "lang"
* item[13].text.extension[0].extension[0].valueCode = #ru
* item[13].text.extension[0].extension[1].url = "content"
* item[13].text.extension[0].extension[1].valueString = "Были ли у вас когда-нибудь инфекции, передающиеся половым путем?"
* item[13].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[13].type = #coding
* item[13].repeats = false
* item[13].answerConstraint = #optionsOnly
* item[13].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-cervical-sti-history-vs"
* item[14].linkId = "113"
* item[14].text = "Sizda hech qachon OIV infeksiyasi aniqlanganmi?"
* item[14].text.extension[0].extension[0].url = "lang"
* item[14].text.extension[0].extension[0].valueCode = #ru
* item[14].text.extension[0].extension[1].url = "content"
* item[14].text.extension[0].extension[1].valueString = "Была ли у вас когда-нибудь обнаружена ВИЧ-инфекция?"
* item[14].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[14].type = #coding
* item[14].repeats = false
* item[14].answerConstraint = #optionsOnly
* item[14].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-cervical-hiv-history-vs"
* item[15].linkId = "114"
* item[15].text = "Onangiz yoki opa-singillaringizning bachadon bo‘yni saratoni bo‘lganmi?"
* item[15].text.extension[0].extension[0].url = "lang"
* item[15].text.extension[0].extension[0].valueCode = #ru
* item[15].text.extension[0].extension[1].url = "content"
* item[15].text.extension[0].extension[1].valueString = "Были ли у вашей матери или сестер РШМ?"
* item[15].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[15].type = #coding
* item[15].repeats = false
* item[15].answerConstraint = #optionsOnly
* item[15].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-cervical-family-cancer-history-vs"
* item[16].linkId = "115"
* item[16].text = "Sizda OPVga qarshi vaksinatsiya o‘tkazilganmi?"
* item[16].text.extension[0].extension[0].url = "lang"
* item[16].text.extension[0].extension[0].valueCode = #ru
* item[16].text.extension[0].extension[1].url = "content"
* item[16].text.extension[0].extension[1].valueString = "Проводилась ли вам вакцинация от ВПЧ?"
* item[16].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[16].type = #boolean
* item[16].repeats = false
* item[17].linkId = "116"
* item[17].text = "Sizda kontakt qon ketishlar bo‘lganmi?"
* item[17].text.extension[0].extension[0].url = "lang"
* item[17].text.extension[0].extension[0].valueCode = #ru
* item[17].text.extension[0].extension[1].url = "content"
* item[17].text.extension[0].extension[1].valueString = "Были ли у вас контактные кровотечения?"
* item[17].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[17].type = #boolean
* item[17].repeats = false
* item[18].linkId = "statusRisk"
* item[18].text = "Hisoblangan bachadon bo‘yni saratoni xavfi"
* item[18].text.extension[0].extension[0].url = "lang"
* item[18].text.extension[0].extension[0].valueCode = #ru
* item[18].text.extension[0].extension[1].url = "content"
* item[18].text.extension[0].extension[1].valueString = "Рассчитанный риск рака шейки матки"
* item[18].text.extension[0].url = "http://hl7.org/fhir/StructureDefinition/translation"
* item[18].type = #coding
* item[18].repeats = false
* item[18].readOnly = true
* item[18].answerConstraint = #optionsOnly
* item[18].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-risk-level-vs"

// Source: Questionnaire-woman-exam.json
Instance: ScreeningWomanExamQuestionnaire
InstanceOf: UZCoreQuestionnaire
Usage: #definition
* id = "screening-woman-exam"
* language = #ru
* url = "https://dhp.uz/fhir/integrations/Questionnaire/screening-woman-exam"
* identifier[0].system = "https://dhp.uz/fhir/integrations/sid/screening/questionnaire-code"
* identifier[0].value = "WOMAN_CHECKUP"
* version = "1.0.0"
* status = #active
* useContext[0].code = $usage-context-type#program
* useContext[0].valueCodeableConcept = $integration-area#screening
* name = "ScreeningWomanExamQuestionnaire"
* title = "Осмотр женщины"
* subjectType[0] = #Patient
* date = 2026-07-30
* publisher = "DHP"
* description = "Опросник медицинского осмотра женщины. linkId клинических вопросов соответствует спецификации интеграции компонента скрининга."
* item[0].linkId = "complaints"
* item[0].text = "Жалобы"
* item[0].type = #group
* item[0].item[0].linkId = "cervical-complaints"
* item[0].item[0].text = "Жалобы по шейке матки"
* item[0].item[0].type = #group
* item[0].item[0].item[0].linkId = "cervical-postcoital-bleeding"
* item[0].item[0].item[0].text = "Кровянистые выделения после полового контакта"
* item[0].item[0].item[0].type = #boolean
* item[0].item[0].item[1].linkId = "cervical-acyclic-bleeding"
* item[0].item[0].item[1].text = "Кровянистые выделения вне зависимости от менструального цикла (ациклические)"
* item[0].item[0].item[1].type = #boolean
* item[0].item[0].item[2].linkId = "cervical-watery-discharge"
* item[0].item[0].item[2].text = "Водянистые выделения из половых путей"
* item[0].item[0].item[2].type = #boolean
* item[0].item[0].item[3].linkId = "cervical-leg-edema"
* item[0].item[0].item[3].text = "Отеки нижних конечностей"
* item[0].item[0].item[3].type = #boolean
* item[0].item[0].item[4].linkId = "cervical-menstrual-dysfunction"
* item[0].item[0].item[4].text = "Нарушение менструальной функции"
* item[0].item[0].item[4].type = #boolean
* item[0].item[0].item[5].linkId = "cervical-menopausal-bleeding"
* item[0].item[0].item[5].text = "Кровянистые выделения из половых путей во время менопаузы"
* item[0].item[0].item[5].type = #boolean
* item[0].item[0].item[6].linkId = "cervical-lower-abdominal-back-pain"
* item[0].item[0].item[6].text = "Боли внизу живота, в пояснице"
* item[0].item[0].item[6].type = #boolean
* item[0].item[0].item[7].linkId = "cervical-complaints-onset"
* item[0].item[0].item[7].text = "Когда начали беспокоить вышеуказанные жалобы?"
* item[0].item[0].item[7].type = #coding
* item[0].item[0].item[7].repeats = false
* item[0].item[0].item[7].answerConstraint = #optionsOnly
* item[0].item[0].item[7].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-medical-exam-complaint-onset-vs"
* item[0].item[1].linkId = "breast-complaints"
* item[0].item[1].text = "Жалобы по молочной железе"
* item[0].item[1].type = #group
* item[0].item[1].item[0].linkId = "breast-lump-or-axillary-mass"
* item[0].item[1].item[0].text = "Уплотнение или наличие образования в молочной железе, в подмышечной области"
* item[0].item[1].item[0].type = #boolean
* item[0].item[1].item[1].linkId = "breast-skin-retraction-or-peau-dorange"
* item[0].item[1].item[1].text = "Изменения в кожном покрове: втяжение кожи, припухлость, кожа в виде «лимонной корки»"
* item[0].item[1].item[1].type = #boolean
* item[0].item[1].item[2].linkId = "breast-skin-color-thickening-edema"
* item[0].item[1].item[2].text = "Изменения цвета кожи: покраснение, утолщение и нагрубание кожи, появление отёка"
* item[0].item[1].item[2].type = #boolean
* item[0].item[1].item[3].linkId = "breast-nipple-retraction-flattening"
* item[0].item[1].item[3].text = "Изменения соска: втяжение или уплощение соска"
* item[0].item[1].item[3].type = #boolean
* item[0].item[1].item[4].linkId = "breast-nipple-crust"
* item[0].item[1].item[4].text = "Появление корочки на коже соска"
* item[0].item[1].item[4].type = #boolean
* item[0].item[1].item[5].linkId = "breast-serous-or-bloody-discharge"
* item[0].item[1].item[5].text = "Выделения из соска сукровичного или кровянистого характера"
* item[0].item[1].item[5].type = #boolean
* item[0].item[1].item[6].linkId = "breast-shape-change"
* item[0].item[1].item[6].text = "Изменения формы молочной железы: деформация, увеличение молочной железы"
* item[0].item[1].item[6].type = #boolean
* item[0].item[1].item[7].linkId = "breast-pain"
* item[0].item[1].item[7].text = "Боль в груди"
* item[0].item[1].item[7].type = #boolean
* item[0].item[1].item[8].linkId = "breast-complaints-onset"
* item[0].item[1].item[8].text = "Когда начали беспокоить вышеуказанные жалобы?"
* item[0].item[1].item[8].type = #coding
* item[0].item[1].item[8].repeats = false
* item[0].item[1].item[8].answerConstraint = #optionsOnly
* item[0].item[1].item[8].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-medical-exam-complaint-onset-vs"
* item[1].linkId = "vitae-anamnesis"
* item[1].text = "Анамнез Vitae"
* item[1].type = #group
* item[1].item[0].linkId = "childhood-infections"
* item[1].item[0].text = "Перенесённые инфекции в детстве"
* item[1].item[0].type = #coding
* item[1].item[0].repeats = true
* item[1].item[0].answerConstraint = #optionsOnly
* item[1].item[0].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-childhood-infection-vs"
* item[1].item[1].linkId = "childhood-infections-comment"
* item[1].item[1].text = "Перенесённые инфекции в детстве (комментарий)"
* item[1].item[1].type = #string
* item[1].item[2].linkId = "previous-diseases"
* item[1].item[2].text = "Перенесённые болезни"
* item[1].item[2].type = #string
* item[1].item[3].linkId = "previous-operations"
* item[1].item[3].text = "Перенесённые операции"
* item[1].item[3].type = #coding
* item[1].item[3].repeats = true
* item[1].item[3].answerConstraint = #optionsOnly
* item[1].item[3].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-previous-operation-vs"
* item[1].item[4].linkId = "previous-operations-comment"
* item[1].item[4].text = "Перенесённые операции (комментарий)"
* item[1].item[4].type = #string
* item[1].item[5].linkId = "hereditary-diseases"
* item[1].item[5].text = "Наследственные болезни"
* item[1].item[5].type = #boolean
* item[1].item[6].linkId = "hereditary-diseases-comment"
* item[1].item[6].text = "Наследственные болезни (комментарий)"
* item[1].item[6].type = #string
* item[1].item[7].linkId = "blood-transfusion"
* item[1].item[7].text = "Переливание крови"
* item[1].item[7].type = #boolean
* item[1].item[8].linkId = "blood-transfusion-comment"
* item[1].item[8].text = "Переливание крови (комментарий)"
* item[1].item[8].type = #string
* item[1].item[9].linkId = "allergic-reactions"
* item[1].item[9].text = "Аллергические реакции"
* item[1].item[9].type = #boolean
* item[1].item[10].linkId = "allergic-reactions-comment"
* item[1].item[10].text = "Аллергические реакции (комментарий)"
* item[1].item[10].type = #string
* item[1].item[11].linkId = "menarche-age"
* item[1].item[11].text = "Возраст начала менструаций"
* item[1].item[11].type = #integer
* item[1].item[12].linkId = "menstruation-regular"
* item[1].item[12].text = "Регулярная менструация"
* item[1].item[12].type = #boolean
* item[1].item[13].linkId = "menstrual-cycle-duration"
* item[1].item[13].text = "Длительность цикла (дней)"
* item[1].item[13].type = #integer
* item[1].item[14].linkId = "menstruation-painfulness"
* item[1].item[14].text = "Болезненность менструаций"
* item[1].item[14].type = #coding
* item[1].item[14].repeats = false
* item[1].item[14].answerConstraint = #optionsOnly
* item[1].item[14].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-menstruation-painfulness-vs"
* item[1].item[15].linkId = "menstruation-abundance"
* item[1].item[15].text = "Обильность менструаций"
* item[1].item[15].type = #coding
* item[1].item[15].repeats = false
* item[1].item[15].answerConstraint = #optionsOnly
* item[1].item[15].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-menstruation-abundance-vs"
* item[1].item[16].linkId = "menstruation-onset-after-days"
* item[1].item[16].text = "После скольких дней наступает менструация"
* item[1].item[16].type = #integer
* item[2].linkId = "breast-exam"
* item[2].text = "Осмотр молочных желез"
* item[2].type = #group
* item[2].item[0].linkId = "breast-pain-group"
* item[2].item[0].text = "Болевые ощущения (мастодиния/масталгия)"
* item[2].item[0].type = #group
* item[2].item[0].item[0].linkId = "breast-aching-pulling-burning-pain"
* item[2].item[0].item[0].text = "Ноющая, тянущая или жгучая боль"
* item[2].item[0].item[0].type = #boolean
* item[2].item[0].item[1].linkId = "breast-cyclic-or-constant-pain"
* item[2].item[0].item[1].text = "Циклическая (усиливается перед менструацией) или постоянная"
* item[2].item[0].item[1].type = #boolean
* item[2].item[0].item[2].linkId = "breast-local-or-diffuse-pain"
* item[2].item[0].item[2].text = "Локальная или разлитая"
* item[2].item[0].item[2].type = #boolean
* item[2].item[1].linkId = "breast-changes"
* item[2].item[1].text = "Изменения в молочных железах"
* item[2].item[1].type = #group
* item[2].item[1].item[0].linkId = "breast-palpable-lump"
* item[2].item[1].item[0].text = "Уплотнение или «шарик» при пальпации"
* item[2].item[1].item[0].type = #boolean
* item[2].item[1].item[1].linkId = "breast-unilateral-enlargement-asymmetry"
* item[2].item[1].item[1].text = "Увеличение или асимметрия одной железы"
* item[2].item[1].item[1].type = #boolean
* item[2].item[1].item[2].linkId = "breast-swelling"
* item[2].item[1].item[2].text = "Отёчность"
* item[2].item[1].item[2].type = #boolean
* item[2].item[1].item[3].linkId = "breast-heaviness"
* item[2].item[1].item[3].text = "Ощущение тяжести"
* item[2].item[1].item[3].type = #boolean
* item[2].item[2].linkId = "breast-skin-nipple-changes"
* item[2].item[2].text = "Изменения кожи и соска"
* item[2].item[2].type = #group
* item[2].item[2].item[0].linkId = "breast-skin-or-nipple-retraction"
* item[2].item[2].item[0].text = "Втяжение кожи или соска"
* item[2].item[2].item[0].type = #boolean
* item[2].item[2].item[1].linkId = "breast-redness"
* item[2].item[2].item[1].text = "Покраснение"
* item[2].item[2].item[1].type = #boolean
* item[2].item[2].item[2].linkId = "breast-induration-peau-dorange"
* item[2].item[2].item[2].text = "Уплотнение, «лимонная корка»"
* item[2].item[2].item[2].type = #boolean
* item[2].item[2].item[3].linkId = "breast-desquamation-ulceration"
* item[2].item[2].item[3].text = "Шелушение, язвочки"
* item[2].item[2].item[3].type = #boolean
* item[2].item[3].linkId = "nipple-discharge-type"
* item[2].item[3].text = "Выделения из сосков"
* item[2].item[3].type = #group
* item[2].item[3].item[0].linkId = "nipple-discharge-transparent"
* item[2].item[3].item[0].text = "Прозрачные"
* item[2].item[3].item[0].type = #boolean
* item[2].item[3].item[1].linkId = "nipple-discharge-milky"
* item[2].item[3].item[1].text = "Молочные"
* item[2].item[3].item[1].type = #boolean
* item[2].item[3].item[2].linkId = "nipple-discharge-yellowish"
* item[2].item[3].item[2].text = "Желтоватые"
* item[2].item[3].item[2].type = #boolean
* item[2].item[3].item[3].linkId = "nipple-discharge-greenish"
* item[2].item[3].item[3].text = "Зеленоватые"
* item[2].item[3].item[3].type = #boolean
* item[2].item[3].item[4].linkId = "nipple-discharge-bloody"
* item[2].item[3].item[4].text = "Кровянистые"
* item[2].item[3].item[4].type = #boolean
* item[2].item[4].linkId = "breast-inflammatory"
* item[2].item[4].text = "Воспалительные проявления"
* item[2].item[4].type = #group
* item[2].item[4].item[0].linkId = "breast-inflammatory-redness"
* item[2].item[4].item[0].text = "Покраснение"
* item[2].item[4].item[0].type = #boolean
* item[2].item[4].item[1].linkId = "breast-local-or-general-fever"
* item[2].item[4].item[1].text = "Повышение температуры местно и/или общего тела"
* item[2].item[4].item[1].type = #boolean
* item[2].item[4].item[2].linkId = "breast-engorgement-or-abscess"
* item[2].item[4].item[2].text = "Нагрубание, абсцесс (гнойные выделения)"
* item[2].item[4].item[2].type = #boolean
* item[2].item[5].linkId = "breast-subjective-sensations"
* item[2].item[5].text = "Субъективные ощущения"
* item[2].item[5].type = #group
* item[2].item[5].item[0].linkId = "breast-tension-sensation"
* item[2].item[5].item[0].text = "Чувство напряжения"
* item[2].item[5].item[0].type = #boolean
* item[2].item[5].item[1].linkId = "breast-distension-sensation"
* item[2].item[5].item[1].text = "Чувство распирания"
* item[2].item[5].item[1].type = #boolean
* item[2].item[5].item[2].linkId = "nipple-hypersensitivity"
* item[2].item[5].item[2].text = "Повышенная чувствительность сосков"
* item[2].item[5].item[2].type = #boolean
* item[2].item[5].item[3].linkId = "breast-foreign-body-sensation"
* item[2].item[5].item[3].text = "Ощущение «инородного тела»"
* item[2].item[5].item[3].type = #boolean
* item[2].item[6].linkId = "breast-lymph-nodes"
* item[2].item[6].text = "Состояние лимфатических узлов"
* item[2].item[6].type = #group
* item[2].item[6].item[0].linkId = "axillary-nodes-bilateral-palpable"
* item[2].item[6].item[0].text = "Подмышечные лимфатические узлы пальпируются с обеих сторон"
* item[2].item[6].item[0].type = #boolean
* item[2].item[6].item[1].linkId = "axillary-nodes-unilateral-palpable"
* item[2].item[6].item[1].text = "Подмышечные лимфатические узлы пальпируются с одной стороны"
* item[2].item[6].item[1].type = #boolean
* item[2].item[6].item[2].linkId = "supraclavicular-nodes-palpable"
* item[2].item[6].item[2].text = "Пальпируются надключичные лимфатические узлы"
* item[2].item[6].item[2].type = #boolean
* item[2].item[6].item[3].linkId = "infraclavicular-nodes-palpable"
* item[2].item[6].item[3].text = "Пальпируются подключичные лимфатические узлы"
* item[2].item[6].item[3].type = #boolean
* item[3].linkId = "menstruation-exam"
* item[3].text = "Менструации во время обследования"
* item[3].type = #group
* item[3].item[0].linkId = "regular-menstruation"
* item[3].item[0].text = "Характер при обследовании (регулярные)"
* item[3].item[0].type = #group
* item[3].item[0].item[0].linkId = "regular-menstruation-start-age"
* item[3].item[0].item[0].text = "Возраст начала менструаций (регулярные)"
* item[3].item[0].item[0].type = #integer
* item[3].item[0].item[1].linkId = "regular-menstruation-regularity"
* item[3].item[0].item[1].text = "Менструации регулярные"
* item[3].item[0].item[1].type = #boolean
* item[3].item[0].item[2].linkId = "regular-cycle-duration"
* item[3].item[0].item[2].text = "Длительность цикла (дней)"
* item[3].item[0].item[2].type = #integer
* item[3].item[0].item[3].linkId = "regular-menstruation-painfulness"
* item[3].item[0].item[3].text = "Болезненность менструаций"
* item[3].item[0].item[3].type = #coding
* item[3].item[0].item[3].repeats = false
* item[3].item[0].item[3].answerConstraint = #optionsOnly
* item[3].item[0].item[3].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-menstruation-painfulness-vs"
* item[3].item[0].item[4].linkId = "regular-menstruation-abundance"
* item[3].item[0].item[4].text = "Обильность менструаций"
* item[3].item[0].item[4].type = #coding
* item[3].item[0].item[4].repeats = false
* item[3].item[0].item[4].answerConstraint = #optionsOnly
* item[3].item[0].item[4].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-menstruation-abundance-vs"
* item[3].item[0].item[5].linkId = "regular-menstruation-onset-after-days"
* item[3].item[0].item[5].text = "После скольких дней наступает менструация"
* item[3].item[0].item[5].type = #integer
* item[3].item[1].linkId = "irregular-menstruation"
* item[3].item[1].text = "Характер при обследовании (нерегулярные)"
* item[3].item[1].type = #group
* item[3].item[1].item[0].linkId = "irregular-menstruation-start-age"
* item[3].item[1].item[0].text = "Возраст начала менструаций (нерегулярные)"
* item[3].item[1].item[0].type = #integer
* item[3].item[1].item[1].linkId = "irregular-menstruation-regularity"
* item[3].item[1].item[1].text = "Менструации регулярные"
* item[3].item[1].item[1].type = #boolean
* item[3].item[1].item[2].linkId = "irregular-cycle-duration"
* item[3].item[1].item[2].text = "Длительность цикла (дней)"
* item[3].item[1].item[2].type = #integer
* item[3].item[1].item[3].linkId = "irregular-menstruation-painfulness"
* item[3].item[1].item[3].text = "Болезненность менструаций"
* item[3].item[1].item[3].type = #coding
* item[3].item[1].item[3].repeats = false
* item[3].item[1].item[3].answerConstraint = #optionsOnly
* item[3].item[1].item[3].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-menstruation-painfulness-vs"
* item[3].item[1].item[4].linkId = "irregular-menstruation-abundance"
* item[3].item[1].item[4].text = "Обильность менструаций"
* item[3].item[1].item[4].type = #coding
* item[3].item[1].item[4].repeats = false
* item[3].item[1].item[4].answerConstraint = #optionsOnly
* item[3].item[1].item[4].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-menstruation-abundance-vs"
* item[3].item[1].item[5].linkId = "irregular-menstruation-onset-after-days"
* item[3].item[1].item[5].text = "После скольких дней наступает менструация"
* item[3].item[1].item[5].type = #integer
* item[3].item[2].linkId = "marital-status"
* item[3].item[2].text = "Статус брака"
* item[3].item[2].type = #coding
* item[3].item[2].repeats = false
* item[3].item[2].answerConstraint = #optionsOnly
* item[3].item[2].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-marital-status-vs"
* item[3].item[3].linkId = "marriage-registration-status"
* item[3].item[3].text = "Статус регистрации брака"
* item[3].item[3].type = #coding
* item[3].item[3].repeats = false
* item[3].item[3].answerConstraint = #optionsOnly
* item[3].item[3].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-marriage-registration-status-vs"
* item[3].item[4].linkId = "sexual-debut-age"
* item[3].item[4].text = "Возраст начала половой жизни"
* item[3].item[4].type = #integer
* item[3].item[5].linkId = "last-menstrual-period-date"
* item[3].item[5].text = "Дата последней менструации"
* item[3].item[5].type = #date
* item[3].item[6].linkId = "cycle-day-at-exam"
* item[3].item[6].text = "День менструального цикла на момент осмотра"
* item[3].item[6].type = #integer
* item[4].linkId = "reproductive-function"
* item[4].text = "Репродуктивная функция"
* item[4].type = #group
* item[4].item[0].linkId = "total-pregnancies"
* item[4].item[0].text = "Общее количество беременностей"
* item[4].item[0].type = #integer
* item[4].item[1].linkId = "pregnancy-outcome-types"
* item[4].item[1].text = "Типы исходов беременностей"
* item[4].item[1].type = #coding
* item[4].item[1].repeats = true
* item[4].item[1].answerConstraint = #optionsOnly
* item[4].item[1].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-pregnancy-outcome-vs"
* item[4].item[2].linkId = "living-children-count"
* item[4].item[2].text = "Количество живых детей"
* item[4].item[2].type = #integer
* item[4].item[3].linkId = "deceased-children-count"
* item[4].item[3].text = "Количество погибших детей"
* item[4].item[3].type = #integer
* item[4].item[4].linkId = "pregnancy-abortion-complications"
* item[4].item[4].text = "Осложнения после беременности/абортов"
* item[4].item[4].type = #coding
* item[4].item[4].repeats = true
* item[4].item[4].answerConstraint = #optionsOnly
* item[4].item[4].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-post-pregnancy-complication-vs"
* item[4].item[5].linkId = "gynecological-diseases-history"
* item[4].item[5].text = "Гинекологические заболевания в анамнезе"
* item[4].item[5].type = #coding
* item[4].item[5].repeats = true
* item[4].item[5].answerConstraint = #optionsOnly
* item[4].item[5].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-gynecological-disease-history-vs"
* item[5].linkId = "surgical-procedure"
* item[5].text = "Гинекологические операции"
* item[5].type = #group
* item[5].item[0].linkId = "hysterosalpingography-1"
* item[5].item[0].text = "Гистеросальпингография"
* item[5].item[0].type = #boolean
* item[5].item[1].linkId = "hysterosalpingography-1-comment"
* item[5].item[1].text = "Гистеросальпингография (комментарий)"
* item[5].item[1].type = #string
* item[5].item[2].linkId = "diagnostic-curettage"
* item[5].item[2].text = "Диагностическое выскабливание"
* item[5].item[2].type = #boolean
* item[5].item[3].linkId = "diagnostic-curettage-comment"
* item[5].item[3].text = "Диагностическое выскабливание (комментарий)"
* item[5].item[3].type = #string
* item[5].item[4].linkId = "cervical-biopsy-history"
* item[5].item[4].text = "Биопсия шейки матки"
* item[5].item[4].type = #boolean
* item[5].item[5].linkId = "cervical-biopsy-history-comment"
* item[5].item[5].text = "Биопсия шейки матки (комментарий)"
* item[5].item[5].type = #string
* item[5].item[6].linkId = "cervical-conization-history"
* item[5].item[6].text = "Конизация шейки матки"
* item[5].item[6].type = #boolean
* item[5].item[7].linkId = "cervical-conization-history-comment"
* item[5].item[7].text = "Конизация шейки матки (комментарий)"
* item[5].item[7].type = #string
* item[5].item[8].linkId = "cervical-amputation-history"
* item[5].item[8].text = "Ампутация шейки матки"
* item[5].item[8].type = #boolean
* item[5].item[9].linkId = "cervical-amputation-history-comment"
* item[5].item[9].text = "Ампутация шейки матки (комментарий)"
* item[5].item[9].type = #string
* item[5].item[10].linkId = "cervical-polyp-removal"
* item[5].item[10].text = "Удаление полипа шейки матки"
* item[5].item[10].type = #boolean
* item[5].item[11].linkId = "cervical-polyp-removal-comment"
* item[5].item[11].text = "Удаление полипа шейки матки (комментарий)"
* item[5].item[11].type = #string
* item[5].item[12].linkId = "endometrial-polyp-removal"
* item[5].item[12].text = "Удаление полипа эндометрия (тела матки)"
* item[5].item[12].type = #boolean
* item[5].item[13].linkId = "endometrial-polyp-removal-comment"
* item[5].item[13].text = "Удаление полипа эндометрия (тела матки) (комментарий)"
* item[5].item[13].type = #string
* item[5].item[14].linkId = "vaginal-plastic-surgery"
* item[5].item[14].text = "Пластика влагалища"
* item[5].item[14].type = #boolean
* item[5].item[15].linkId = "vaginal-plastic-surgery-comment"
* item[5].item[15].text = "Пластика влагалища (комментарий)"
* item[5].item[15].type = #string
* item[5].item[16].linkId = "laparotomy"
* item[5].item[16].text = "Лапаротомия (разрез брюшной стенки)"
* item[5].item[16].type = #boolean
* item[5].item[17].linkId = "laparotomy-comment"
* item[5].item[17].text = "Лапаротомия (разрез брюшной стенки) (комментарий)"
* item[5].item[17].type = #string
* item[5].item[18].linkId = "midline-laparotomy"
* item[5].item[18].text = "Срединная лапаротомия (пояснение к пункту выше)"
* item[5].item[18].type = #boolean
* item[5].item[19].linkId = "midline-laparotomy-comment"
* item[5].item[19].text = "Срединная лапаротомия (пояснение к пункту выше) (комментарий)"
* item[5].item[19].type = #string
* item[5].item[20].linkId = "pfannenstiel-incision"
* item[5].item[20].text = "Разрез по Пфанненштилю"
* item[5].item[20].type = #boolean
* item[5].item[21].linkId = "pfannenstiel-incision-comment"
* item[5].item[21].text = "Разрез по Пфанненштилю (комментарий)"
* item[5].item[21].type = #string
* item[5].item[22].linkId = "joel-cohen-incision"
* item[5].item[22].text = "Разрез по Джоэлю-Кохену"
* item[5].item[22].type = #boolean
* item[5].item[23].linkId = "joel-cohen-incision-comment"
* item[5].item[23].text = "Разрез по Джоэлю-Кохену (комментарий)"
* item[5].item[23].type = #string
* item[5].item[24].linkId = "laparoscopy"
* item[5].item[24].text = "Лапароскопия"
* item[5].item[24].type = #boolean
* item[5].item[25].linkId = "laparoscopy-comment"
* item[5].item[25].text = "Лапароскопия (комментарий)"
* item[5].item[25].type = #string
* item[5].item[26].linkId = "myomectomy"
* item[5].item[26].text = "Миомэктомия (удаление миомы матки)"
* item[5].item[26].type = #boolean
* item[5].item[27].linkId = "myomectomy-comment"
* item[5].item[27].text = "Миомэктомия (удаление миомы матки) (комментарий)"
* item[5].item[27].type = #string
* item[5].item[28].linkId = "salpingectomy"
* item[5].item[28].text = "Удаление маточной трубы"
* item[5].item[28].type = #boolean
* item[5].item[29].linkId = "salpingectomy-comment"
* item[5].item[29].text = "Удаление маточной трубы (комментарий)"
* item[5].item[29].type = #string
* item[5].item[30].linkId = "salpingotomy"
* item[5].item[30].text = "Вскрытие маточной трубы"
* item[5].item[30].type = #boolean
* item[5].item[31].linkId = "salpingotomy-comment"
* item[5].item[31].text = "Вскрытие маточной трубы (комментарий)"
* item[5].item[31].type = #string
* item[5].item[32].linkId = "cyst-removal"
* item[5].item[32].text = "Удаление кисты"
* item[5].item[32].type = #boolean
* item[5].item[33].linkId = "cyst-removal-comment"
* item[5].item[33].text = "Удаление кисты (комментарий)"
* item[5].item[33].type = #string
* item[5].item[34].linkId = "oophorectomy"
* item[5].item[34].text = "Резекция яичника"
* item[5].item[34].type = #boolean
* item[5].item[35].linkId = "oophorectomy-comment"
* item[5].item[35].text = "Резекция яичника (комментарий)"
* item[5].item[35].type = #string
* item[5].item[36].linkId = "adnexectomy"
* item[5].item[36].text = "Удаление придатков матки"
* item[5].item[36].type = #boolean
* item[5].item[37].linkId = "adnexectomy-comment"
* item[5].item[37].text = "Удаление придатков матки (комментарий)"
* item[5].item[37].type = #string
* item[5].item[38].linkId = "subtotal-hysterectomy"
* item[5].item[38].text = "Субтотальная гистерэктомия"
* item[5].item[38].type = #boolean
* item[5].item[39].linkId = "subtotal-hysterectomy-comment"
* item[5].item[39].text = "Субтотальная гистерэктомия (комментарий)"
* item[5].item[39].type = #string
* item[5].item[40].linkId = "total-hysterectomy"
* item[5].item[40].text = "Тотальная (полная) гистерэктомия"
* item[5].item[40].type = #boolean
* item[5].item[41].linkId = "total-hysterectomy-comment"
* item[5].item[41].text = "Тотальная (полная) гистерэктомия (комментарий)"
* item[5].item[41].type = #string
* item[5].item[42].linkId = "with-adnexa"
* item[5].item[42].text = "С придатками"
* item[5].item[42].type = #boolean
* item[5].item[43].linkId = "with-adnexa-comment"
* item[5].item[43].text = "С придатками (комментарий)"
* item[5].item[43].type = #string
* item[5].item[44].linkId = "without-adnexa"
* item[5].item[44].text = "Без придатков"
* item[5].item[44].type = #boolean
* item[5].item[45].linkId = "without-adnexa-comment"
* item[5].item[45].text = "Без придатков (комментарий)"
* item[5].item[45].type = #string
* item[6].linkId = "contraception"
* item[6].text = "Методы контрацепции"
* item[6].type = #group
* item[6].item[0].linkId = "contraception-condom"
* item[6].item[0].text = "Презерватив"
* item[6].item[0].type = #boolean
* item[6].item[1].linkId = "contraception-coc"
* item[6].item[1].text = "Комбинированные оральные контрацептивы (КОК)"
* item[6].item[1].type = #boolean
* item[6].item[2].linkId = "contraception-iud-spiral"
* item[6].item[2].text = "Внутриматочная контрацепция (спираль)"
* item[6].item[2].type = #boolean
* item[6].item[3].linkId = "contraception-vaginal-suppositories"
* item[6].item[3].text = "Свечи (вагинальные суппозитории)"
* item[6].item[3].type = #boolean
* item[6].item[4].linkId = "contraception-withdrawal"
* item[6].item[4].text = "Прерванный половой акт"
* item[6].item[4].type = #boolean
* item[6].item[5].linkId = "contraception-surgical-sterilization"
* item[6].item[5].text = "Добровольная хирургическая стерилизация"
* item[6].item[5].type = #boolean
* item[6].item[6].linkId = "contraception-intrauterine"
* item[6].item[6].text = "Внутриматочные контрацептивы"
* item[6].item[6].type = #boolean
* item[6].item[7].linkId = "contraception-natural"
* item[6].item[7].text = "Естественные методы"
* item[6].item[7].type = #boolean
* item[6].item[8].linkId = "contraception-other"
* item[6].item[8].text = "Другое"
* item[6].item[8].type = #boolean
* item[6].item[9].linkId = "contraception-other-comment"
* item[6].item[9].text = "Другие (комментарий)"
* item[6].item[9].type = #string
* item[7].linkId = "general-obesity"
* item[7].text = "Общее состояние и степень ожирения"
* item[7].type = #group
* item[7].item[0].linkId = "general-condition"
* item[7].item[0].text = "Общее состояние"
* item[7].item[0].type = #coding
* item[7].item[0].repeats = false
* item[7].item[0].answerConstraint = #optionsOnly
* item[7].item[0].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-general-condition-vs"
* item[7].item[1].linkId = "obesity-degree"
* item[7].item[1].text = "Степень ожирения"
* item[7].item[1].type = #coding
* item[7].item[1].repeats = false
* item[7].item[1].answerConstraint = #optionsOnly
* item[7].item[1].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-obesity-degree-vs"
* item[8].linkId = "hirsutism-general-exam"
* item[8].text = "Степень гирсутизма и дополнительные данные общего осмотра"
* item[8].type = #group
* item[8].item[0].linkId = "hirsutism-face"
* item[8].item[0].text = "На лице"
* item[8].item[0].type = #coding
* item[8].item[0].repeats = true
* item[8].item[0].answerConstraint = #optionsOnly
* item[8].item[0].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-hirsutism-face-vs"
* item[8].item[1].linkId = "hirsutism-thighs"
* item[8].item[1].text = "На бедрах"
* item[8].item[1].type = #coding
* item[8].item[1].repeats = true
* item[8].item[1].answerConstraint = #optionsOnly
* item[8].item[1].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-hirsutism-thigh-vs"
* item[8].item[2].linkId = "hirsutism-abdomen"
* item[8].item[2].text = "Другое / на животе"
* item[8].item[2].type = #coding
* item[8].item[2].repeats = true
* item[8].item[2].answerConstraint = #optionsOnly
* item[8].item[2].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-hirsutism-other-vs"
* item[8].item[3].linkId = "stretch-marks-color"
* item[8].item[3].text = "Цвет растяжек"
* item[8].item[3].type = #string
* item[8].item[4].linkId = "stretch-marks-count"
* item[8].item[4].text = "Кол-во растяжек"
* item[8].item[4].type = #integer
* item[8].item[5].linkId = "stretch-marks-location"
* item[8].item[5].text = "Локализация растяжек"
* item[8].item[5].type = #string
* item[8].item[6].linkId = "thyroid-assessment"
* item[8].item[6].text = "Оценка щитовидной железы"
* item[8].item[6].type = #boolean
* item[8].item[7].linkId = "thyroid-enlargement-degree"
* item[8].item[7].text = "Степень увеличения"
* item[8].item[7].type = #coding
* item[8].item[7].repeats = true
* item[8].item[7].answerConstraint = #optionsOnly
* item[8].item[7].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-thyroid-enlargement-degree-vs"
* item[8].item[8].linkId = "breast-assessment"
* item[8].item[8].text = "Оценка молочных желез"
* item[8].item[8].type = #coding
* item[8].item[8].repeats = true
* item[8].item[8].answerConstraint = #optionsOnly
* item[8].item[8].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-breast-assessment-vs"
* item[8].item[9].linkId = "breast-palpation-assessment"
* item[8].item[9].text = "При пальпации"
* item[8].item[9].type = #coding
* item[8].item[9].repeats = true
* item[8].item[9].answerConstraint = #optionsOnly
* item[8].item[9].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-breast-palpation-assessment-vs"
* item[8].item[10].linkId = "axillary-nodes-palpable"
* item[8].item[10].text = "Подмышечные лимфатические узлы определяются при пальпации"
* item[8].item[10].type = #boolean
* item[8].item[11].linkId = "nipple-hair"
* item[8].item[11].text = "Оволосение сосков молочных желез"
* item[8].item[11].type = #boolean
* item[8].item[12].linkId = "nipple-discharge-present"
* item[8].item[12].text = "Выделения из сосков"
* item[8].item[12].type = #boolean
* item[8].item[13].linkId = "nipple-discharge-comment"
* item[8].item[13].text = "Выделения из сосков (комментарий)"
* item[8].item[13].type = #string
* item[8].item[14].linkId = "liver-spleen-palpable"
* item[8].item[14].text = "Печень/селезенка пальпируются?"
* item[8].item[14].type = #boolean
* item[8].item[15].linkId = "urination"
* item[8].item[15].text = "Мочеиспускание"
* item[8].item[15].type = #coding
* item[8].item[15].repeats = false
* item[8].item[15].answerConstraint = #optionsOnly
* item[8].item[15].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-urination-characteristic-vs"
* item[8].item[16].linkId = "urination-times-per-day"
* item[8].item[16].text = "Кол-во раз в сутки"
* item[8].item[16].type = #integer
* item[8].item[17].linkId = "defecation-times-per-day"
* item[8].item[17].text = "Дефекация (кол-во раз в сутки)"
* item[8].item[17].type = #integer
* item[8].item[18].linkId = "constipation-tendency"
* item[8].item[18].text = "Склонность к запорам"
* item[8].item[18].type = #boolean
* item[8].item[19].linkId = "leg-varicose-veins"
* item[8].item[19].text = "Варикозное расширение вен ног"
* item[8].item[19].type = #boolean
* item[9].linkId = "gynecological-status"
* item[9].text = "Гинекологическое состояние"
* item[9].type = #group
* item[9].item[0].linkId = "external-genitalia-normal"
* item[9].item[0].text = "Развитие наружных половых органов"
* item[9].item[0].type = #coding
* item[9].item[0].repeats = false
* item[9].item[0].answerConstraint = #optionsOnly
* item[9].item[0].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-external-genitalia-development-vs"
* item[9].item[1].linkId = "genital-slit-closed"
* item[9].item[1].text = "Состояние половой щели"
* item[9].item[1].type = #coding
* item[9].item[1].repeats = false
* item[9].item[1].answerConstraint = #optionsOnly
* item[9].item[1].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-genital-slit-state-vs"
* item[9].item[2].linkId = "vaginal-mucosa-pink"
* item[9].item[2].text = "Состояние слизистой оболочки влагалища"
* item[9].item[2].type = #coding
* item[9].item[2].repeats = false
* item[9].item[2].answerConstraint = #optionsOnly
* item[9].item[2].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-vaginal-mucosa-condition-vs"
* item[9].item[3].linkId = "vaginal-os-punctate"
* item[9].item[3].text = "Форма зева влагалища"
* item[9].item[3].type = #coding
* item[9].item[3].repeats = false
* item[9].item[3].answerConstraint = #optionsOnly
* item[9].item[3].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-vaginal-os-shape-vs"
* item[9].item[4].linkId = "vagina-parous"
* item[9].item[4].text = "Состояние влагалища с учётом паритета"
* item[9].item[4].type = #coding
* item[9].item[4].repeats = false
* item[9].item[4].answerConstraint = #optionsOnly
* item[9].item[4].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-vaginal-parity-status-vs"
* item[9].item[5].linkId = "external-cervical-os-closed"
* item[9].item[5].text = "Состояние наружного зева шейки матки"
* item[9].item[5].type = #coding
* item[9].item[5].repeats = false
* item[9].item[5].answerConstraint = #optionsOnly
* item[9].item[5].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-external-cervical-os-state-vs"
* item[9].item[6].linkId = "cervicitis-absent"
* item[9].item[6].text = "Наличие признаков цервицита"
* item[9].item[6].type = #coding
* item[9].item[6].repeats = false
* item[9].item[6].answerConstraint = #optionsOnly
* item[9].item[6].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-cervicitis-status-vs"
* item[9].item[7].linkId = "hair-growth"
* item[9].item[7].text = "Оволосение"
* item[9].item[7].type = #coding
* item[9].item[7].repeats = true
* item[9].item[7].answerConstraint = #optionsOnly
* item[9].item[7].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-pubic-hair-pattern-vs"
* item[9].item[8].linkId = "tvme"
* item[9].item[8].text = "ТВМЕ / опущение стенок влагалища"
* item[9].item[8].type = #coding
* item[9].item[8].repeats = true
* item[9].item[8].answerConstraint = #optionsOnly
* item[9].item[8].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-vaginal-wall-prolapse-vs"
* item[9].item[9].linkId = "uterus-vagina-visual-condition"
* item[9].item[9].text = "Состояние матки и влагалища (осмотр)"
* item[9].item[9].type = #coding
* item[9].item[9].repeats = true
* item[9].item[9].answerConstraint = #optionsOnly
* item[9].item[9].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-uterus-vagina-visual-condition-vs"
* item[9].item[10].linkId = "vaginal-discharge"
* item[9].item[10].text = "Выделения из влагалища"
* item[9].item[10].type = #coding
* item[9].item[10].repeats = true
* item[9].item[10].answerConstraint = #optionsOnly
* item[9].item[10].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-vaginal-discharge-type-vs"
* item[9].item[11].linkId = "vaginal-discharge-comment"
* item[9].item[11].text = "Выделения из влагалища (комментарий)"
* item[9].item[11].type = #string
* item[9].item[12].linkId = "vaginal-discharge-quantity"
* item[9].item[12].text = "Кол-во"
* item[9].item[12].type = #coding
* item[9].item[12].repeats = false
* item[9].item[12].answerConstraint = #optionsOnly
* item[9].item[12].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-vaginal-discharge-amount-vs"
* item[9].item[13].linkId = "vaginal-discharge-odor"
* item[9].item[13].text = "Запах"
* item[9].item[13].type = #coding
* item[9].item[13].repeats = false
* item[9].item[13].answerConstraint = #optionsOnly
* item[9].item[13].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-vaginal-discharge-odor-vs"
* item[9].item[14].linkId = "cervix-condition"
* item[9].item[14].text = "Шейка матки"
* item[9].item[14].type = #coding
* item[9].item[14].repeats = false
* item[9].item[14].answerConstraint = #optionsOnly
* item[9].item[14].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-cervix-condition-vs"
* item[9].item[15].linkId = "cervix-size"
* item[9].item[15].text = "Размер шейки матки"
* item[9].item[15].type = #coding
* item[9].item[15].repeats = false
* item[9].item[15].answerConstraint = #optionsOnly
* item[9].item[15].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-cervix-size-vs"
* item[9].item[16].linkId = "pupil-sign-present"
* item[9].item[16].text = "Симптом «зрачка» присутствует"
* item[9].item[16].type = #boolean
* item[9].item[17].linkId = "cervical-mucus-stretchability"
* item[9].item[17].text = "Симптом растяжимости слизистой шейки"
* item[9].item[17].type = #boolean
* item[9].item[18].linkId = "cervix-length"
* item[9].item[18].text = "Длина шейки матки"
* item[9].item[18].type = #decimal
* item[10].linkId = "uterine-body"
* item[10].text = "Тело матки и придатки"
* item[10].type = #group
* item[10].item[0].linkId = "uterus-size-normal"
* item[10].item[0].text = "Размер матки нормальный"
* item[10].item[0].type = #boolean
* item[10].item[1].linkId = "uterus-size-enlarged"
* item[10].item[1].text = "Увеличенный размер"
* item[10].item[1].type = #boolean
* item[10].item[2].linkId = "uterus-size-below-normal"
* item[10].item[2].text = "Меньше нормы"
* item[10].item[2].type = #boolean
* item[10].item[3].linkId = "uterus-painful"
* item[10].item[3].text = "Болезненная"
* item[10].item[3].type = #boolean
* item[10].item[4].linkId = "uterus-dense"
* item[10].item[4].text = "Плотная"
* item[10].item[4].type = #boolean
* item[10].item[5].linkId = "left-adnexa-enlarged"
* item[10].item[5].text = "Левый придаток увеличен"
* item[10].item[5].type = #boolean
* item[10].item[6].linkId = "left-adnexa-size-cm"
* item[10].item[6].text = "Размер левого придатка в см."
* item[10].item[6].type = #decimal
* item[10].item[7].linkId = "right-adnexa-defined"
* item[10].item[7].text = "Правый придаток определяется"
* item[10].item[7].type = #boolean
* item[10].item[8].linkId = "right-adnexa-size-cm"
* item[10].item[8].text = "Размер правого придатка в см."
* item[10].item[8].type = #decimal
* item[10].item[9].linkId = "uterine-vaults"
* item[10].item[9].text = "Своды матки"
* item[10].item[9].type = #coding
* item[10].item[9].repeats = false
* item[10].item[9].answerConstraint = #optionsOnly
* item[10].item[9].answerValueSet = "https://terminology.dhp.uz/fhir/integrations/ValueSet/screening-uterine-vault-status-vs"

* item[11].linkId = "morbi-anamnesis"
* item[11].text = "Анамнез заболевания (Anamnesis morbi)"
* item[11].type = #text
* item[11].repeats = false
